apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  failurePolicy: reinstall
  valuesContent: |-
    additionalArguments:
      - --certificatesresolvers.le.acme.email=varun.mehrotra@webguru.ca
      - --certificatesresolvers.le.acme.storage=/data/acme.json
      - --certificatesresolvers.le.acme.tlschallenge=true
      - --metrics.prometheus.addentrypointslabels=true
      - --metrics.prometheus.addrouterslabels=true
      - --metrics.prometheus.addserviceslabels=true

    ports:
      web:
        exposedPort: 80
        redirections:
          entryPoint:
            to: websecure
            scheme: https
            permanent: true

      websecure:
        exposedPort: 443
        tls:
          enabled: true

    persistence:
      enabled: true
      path: /data
      size: 1Gi
      accessMode: ReadWriteOnce
