-- Generated from McDonald's Canada menu and item detail pages.
-- Source: https://www.mcdonalds.com/ca/en-ca/full-menu.html
truncate table ingredient_allergens, menu_item_ingredients, menu_items, ingredients, allergens, restaurants restart identity cascade;

insert into restaurants (id, slug, name, description, cuisine_hint, sort_order) values
  ('mcdonalds-canada', 'mcdonalds-canada', 'McDonald''s Canada', 'Live McDonald''s Canada menu data sourced from current product pages and ingredient details.', 'Burgers, breakfast, chicken, beverages, desserts, and more', 1);

insert into allergens (id, name) values
  ('barley', 'barley'),
  ('egg', 'egg'),
  ('fish', 'fish'),
  ('milk', 'milk'),
  ('mustard', 'mustard'),
  ('oat', 'oat'),
  ('sesame-seeds', 'sesame seeds'),
  ('soy', 'soy'),
  ('sulphites', 'sulphites'),
  ('tree-nuts', 'tree nuts'),
  ('wheat', 'wheat')
;

insert into ingredients (id, name) values
  ('1-partly-skimmed-chocolate-milk', '1% Partly Skimmed Chocolate Milk'),
  ('1-partly-skimmed-milk', '1% Partly Skimmed Milk'),
  ('18-cream', '18% Cream'),
  ('2-milk', '2% milk'),
  ('apple-juice', 'Apple Juice'),
  ('apple-slices', 'Apple Slices'),
  ('bacon-slice', 'Bacon Slice'),
  ('baked-apple-pie', 'Baked Apple Pie'),
  ('banana-chocolate-chunk-muffin', 'Banana Chocolate Chunk Muffin'),
  ('barq-s-root-beer', 'Barq''s Root Beer'),
  ('beef-patty', 'Beef Patty'),
  ('berry-mcpops-donut', 'Berry McPops Donut'),
  ('big-mac-bun', 'Big Mac Bun'),
  ('big-mac-sauce', 'Big Mac Sauce'),
  ('blue-raspberry-flavoured-syrup', 'Blue Raspberry Flavoured Syrup'),
  ('blueberry-cream-cheese-pie', 'Blueberry Cream Cheese Pie'),
  ('blueberry-muffin', 'Blueberry Muffin'),
  ('blueberry-pomegranate-smoothie-fruit-base', 'Blueberry Pomegranate Smoothie Fruit Base'),
  ('brewed-coffee', 'Brewed Coffee'),
  ('butter', 'Butter'),
  ('butter-portion-whipped', 'Butter Portion - Whipped'),
  ('cadbury-chocolate', 'Cadbury Chocolate'),
  ('canadian-bacon', 'Canadian Bacon'),
  ('caramel-flavoured-syrup', 'Caramel Flavoured Syrup'),
  ('carrot-muffin', 'Carrot Muffin'),
  ('cheese-curds', 'Cheese Curds'),
  ('chicken-big-mac-patty', 'Chicken Big Mac Patty'),
  ('chicken-mcnuggets', 'Chicken McNuggets'),
  ('chocolate-brownie-muffin-mix', 'Chocolate Brownie Muffin Mix'),
  ('chocolate-chip-muffin', 'Chocolate Chip Muffin'),
  ('chocolate-chunk-cookie', 'Chocolate Chunk Cookie'),
  ('chocolate-syrup', 'Chocolate Syrup'),
  ('coca-cola', 'Coca-Cola'),
  ('coca-cola-zero', 'Coca-Cola Zero'),
  ('coffee-frappe', 'Coffee Frappe'),
  ('cranberry-orange-muffin', 'Cranberry Orange Muffin'),
  ('creamy-chipotle-sauce', 'Creamy Chipotle Sauce'),
  ('creamy-habanero-sauce', 'Creamy Habanero Sauce'),
  ('creme-egg-syrup', 'Creme Egg Syrup'),
  ('crispy-chicken-patty', 'Crispy Chicken Patty'),
  ('crispy-chicken-portion', 'Crispy Chicken Portion'),
  ('crunchy-breaded-veggie-patty', 'Crunchy Breaded Veggie Patty'),
  ('crushed-skor-candy-bars', 'Crushed SKOR Candy Bars'),
  ('crushed-smarties', 'Crushed Smarties'),
  ('cucumber', 'Cucumber'),
  ('dasani-water', 'Dasani Water'),
  ('diet-coke', 'Diet Coke'),
  ('egg', 'Egg'),
  ('egg-mixture', 'Egg Mixture'),
  ('english-muffin', 'English Muffin'),
  ('espresso-coffee', 'Espresso Coffee'),
  ('everything-bagel', 'Everything Bagel'),
  ('filet-o-fish-portion', 'Filet-O-Fish Portion'),
  ('frank-s-redhot-creamy-garlic-sauce', 'Frank''s RedHot® Creamy Garlic Sauce'),
  ('frank-s-redhot-thick-sauce-thick-cayenne-pepper-sauce', 'Frank''s RedHot® Thick Sauce (Thick Cayenne Pepper Sauce)'),
  ('french-fries', 'French Fries'),
  ('french-vanilla-flavoured-syrup', 'French Vanilla Flavoured Syrup'),
  ('fruit-and-fibre-muffin', 'Fruit & Fibre Muffin'),
  ('fruitopia-orange-groove', 'Fruitopia Orange Groove'),
  ('fruitopia-strawberry-passion-awareness', 'Fruitopia Strawberry Passion Awareness'),
  ('fuze-iced-tea', 'Fuze Iced Tea'),
  ('green-onions', 'Green Onions'),
  ('grill-seasoning', 'Grill Seasoning'),
  ('grilled-chicken-portion', 'Grilled Chicken Portion'),
  ('hashbrowns', 'Hashbrowns'),
  ('hazelnut-and-cocoa-mcpops', 'Hazelnut & Cocoa McPops'),
  ('homestyle-mcrib-roll', 'Homestyle McRib Roll'),
  ('hot-caramel-topping', 'Hot Caramel Topping'),
  ('hot-chocolate-packet', 'Hot Chocolate (Packet)'),
  ('hot-fudge-sundae-topping', 'Hot Fudge Sundae Topping'),
  ('hotcake-syrup', 'Hotcake Syrup'),
  ('hotcakes', 'Hotcakes'),
  ('ice', 'Ice'),
  ('junior-chicken-patty', 'Junior Chicken Patty'),
  ('ketchup', 'Ketchup'),
  ('large-cone', 'Large Cone'),
  ('leaf-lettuce', 'Leaf Lettuce'),
  ('lemonade-concentrate', 'Lemonade Concentrate'),
  ('lettuce', 'Lettuce'),
  ('liquid-sugar', 'Liquid Sugar'),
  ('mango-pineapple-fruit-base', 'Mango Pineapple Fruit Base'),
  ('mayonnaise-style-sauce', 'Mayonnaise-Style Sauce'),
  ('mcchicken-portion', 'McChicken Portion'),
  ('mcgriddles-cakes', 'McGriddles Cakes'),
  ('mustard', 'Mustard'),
  ('oat-beverage', 'Oat Beverage'),
  ('onions-dehydrated', 'Onions (dehydrated)'),
  ('orange-juice', 'Orange Juice'),
  ('oreo-mix-in', 'Oreo Mix-in'),
  ('philadelphia-plain-cream-cheese-product', 'Philadelphia Plain Cream Cheese Product'),
  ('pickle-slices', 'Pickle Slices'),
  ('potato-bun', 'Potato Bun'),
  ('poutine-gravy', 'Poutine Gravy'),
  ('premium-ranch-sauce', 'Premium Ranch Sauce'),
  ('premium-tea', 'Premium Tea'),
  ('processed-cheese', 'Processed Cheese'),
  ('quarter-pounder-beef-patty', 'Quarter Pounder Beef Patty'),
  ('rainbow-sprinkle-cookie', 'Rainbow Sprinkle Cookie'),
  ('regular-bagel', 'Regular Bagel'),
  ('regular-bun', 'Regular Bun'),
  ('salt', 'Salt'),
  ('salted-caramel-crunch-topping', 'Salted Caramel Crunch Topping'),
  ('salted-caramel-flavoured-syrup', 'Salted Caramel Flavoured Syrup'),
  ('sausage-patty', 'Sausage Patty'),
  ('sesame-seed-bagel', 'Sesame Seed Bagel'),
  ('sesame-seed-bun', 'Sesame Seed Bun'),
  ('shredded-cheddar-cheese', 'Shredded Cheddar Cheese'),
  ('slivered-onions', 'Slivered Onions'),
  ('smoothie-yogurt-mix', 'Smoothie Yogurt Mix'),
  ('spicy-buffalo-sauce', 'Spicy Buffalo Sauce'),
  ('sprite', 'Sprite'),
  ('strawberry-banana-fruit-smoothie-base', 'Strawberry Banana Fruit Smoothie Base'),
  ('strawberry-sauce', 'Strawberry Sauce'),
  ('strawberry-yogurt-tube', 'Strawberry Yogurt Tube'),
  ('sugar-free-syrup', 'Sugar Free Syrup'),
  ('sweet-chili-sauce', 'Sweet Chili Sauce'),
  ('tartar-sauce', 'Tartar Sauce'),
  ('toasted-s-mores-cookie', 'Toasted S''mores Cookie'),
  ('tomato-slice', 'Tomato Slice'),
  ('tri-colour-tortilla-strips', 'Tri-Colour Tortilla Strips'),
  ('triple-thick-milkshake-chocolate-syrup', 'Triple Thick Milkshake Chocolate Syrup'),
  ('triple-thick-milkshake-strawberry-syrup', 'Triple Thick Milkshake Strawberry Syrup'),
  ('triple-thick-milkshake-vanilla-syrup', 'Triple Thick Milkshake Vanilla Syrup'),
  ('triple-thick-shamrock-shake-syrup', 'Triple Thick Shamrock Shake Syrup'),
  ('vanilla-chai-frapp-base', 'Vanilla Chai Frappé Base'),
  ('vanilla-ice-milk', 'Vanilla Ice Milk'),
  ('water', 'Water'),
  ('watermelon-lime-flavoured-syrup', 'Watermelon Lime Flavoured Syrup'),
  ('whipped-cream', 'Whipped Cream'),
  ('white-chocolate-mcpops', 'White Chocolate McPops'),
  ('white-flour-tortilla', 'White Flour Tortilla')
;

insert into menu_items (id, restaurant_id, name, category, description, sort_order) values
  ('franks-redhot-creamy-garlic-chicken-mcmuffin', 'mcdonalds-canada', 'Frank’s RedHot® Creamy Garlic Chicken McMuffin', 'Breakfast', 'Our signature Chicken McMuffin breakfast sandwich with a creamy garlic kick. A breaded seasoned chicken patty, made with chicken raised on Canadian farms, with a creamy garlic sauce with the taste of Frank’s RedHot®, and a slice of tasty processed cheese, nestled comfortably in a toasty English muffin.', 1),
  ('franks-redhot-creamy-garlic-egg-mcmuffin', 'mcdonalds-canada', 'Frank’s RedHot® Creamy Garlic Egg McMuffin', 'Breakfast', 'Our signature Egg McMuffin breakfast sandwich with a creamy garlic kick. Wake your tastebuds with a freshly cracked Canada Grade A egg topped with Canadian bacon, a slice of tasty processed cheese, and a creamy garlic sauce with the taste of Frank’s RedHot®, all sitting on a toasted English muffin.', 2),
  ('franks-redhot-creamy-garlic-sausage-n-egg-mcmuffin', 'mcdonalds-canada', 'Frank’s RedHot® Creamy Garlic Sausage ‘N Egg McMuffin', 'Breakfast', 'Our signature Sausage ‘N Egg McMuffin breakfast sandwich with a creamy garlic kick. Wake your tastebuds with the savoury taste of sausage, tasty processed cheese and a freshly cracked Canada Grade A egg, topped with a creamy garlic sauce with the taste of Frank’s RedHot®, all sitting on a toasty English muffin.', 3),
  ('franks-redhot-creamy-garlic-bacon-n-egg-mcmuffin', 'mcdonalds-canada', 'Frank’s RedHot® Creamy Garlic Bacon ‘N Egg McMuffin', 'Breakfast', 'Our signature Bacon ‘N Egg McMuffin breakfast sandwich with a creamy garlic kick. Crispy hickory-smoked bacon on a freshly cracked Canada Grade A egg, topped with processed cheese and a creamy garlic sauce with the taste of Frank’s RedHot®, nestled comfortably in a toasty English muffin.', 4),
  ('mighty-mcgriddle', 'mcdonalds-canada', 'Mighty McGriddles', 'Breakfast', 'Get a double portion of hickory-smoked bacon, plus a freshly-cracked Canada Grade A egg, processed cheese and savoury sausage all on two sweet, warm, maple-flavoured griddle cakes. A mighty eat to rid you of your mighty hunger.  Available until 11 AM.', 5),
  ('mighty-mcmuffin', 'mcdonalds-canada', 'Mighty McMuffin', 'Breakfast', 'Get a double portion of hickory-smoked bacon, plus a freshly-cracked Canada Grade A egg , processed cheese and savoury sausage  on a toasted English muffin. A mighty eat to rid you of your mighty hunger.', 6),
  ('spicy-egg-hash-brown-breakfast-wrap', 'mcdonalds-canada', 'Spicy Egg & Hash Brown Breakfast Wrap', 'Breakfast', 'Made with a freshly-cracked Canadian Free Run Egg and processed cheese, topped with Spicy Habanero sauce, shredded lettuce, tomato and a crispy hash brown, all wrapped in a soft white flour tortilla.', 7),
  ('chicken-hash-brown-breakfast-wrap', 'mcdonalds-canada', 'Chicken Breakfast Wrap', 'Breakfast', 'Made with a breaded seasoned chicken patty and processed cheese, topped with mayo-style sauce, shredded lettuce and a crispy hash brown, all wrapped in a soft white flour tortilla.', 8),
  ('sausage-bacon-egg-breakfast-wrap', 'mcdonalds-canada', 'Sausage, Bacon & Egg Breakfast Wrap', 'Breakfast', 'Made with savoury sausage, hickory-smoked bacon, a freshly-cracked Candian Free-Run Egg,  and processed cheese, topped with mayo-style sauce and a crispy hash brown, all  wrapped in a soft white flour tortilla.', 9),
  ('egg-n-cheese-mcmuffin', 'mcdonalds-canada', 'Egg ''N Cheese McMuffin', 'Breakfast', 'Made with a freshly cracked Canada Grade A egg and tasty processed cheese on a perfectly toasted English muffin.', 10),
  ('egg-n-cheese-mcgriddles', 'mcdonalds-canada', 'Egg ''N Cheese McGriddles', 'Breakfast', 'Made with a freshly cracked Canada Grade A egg and processed cheese on two sweet, warm, maple-flavoured griddle cakes.', 11),
  ('egg-blt-mcmuffin', 'mcdonalds-canada', 'Egg BLT McMuffin', 'Breakfast', 'This breakfast sandwich is made with a freshly cracked Canada Grade A egg, topped with crispy hickory smoked bacon (B), crisp lettuce (L) and fresh tomato (T), mayo-style sauce and a slice of processed cheese, served on a toasted English muffin.', 12),
  ('egg-blt-mcmuffin-with-shredded-lettuce', 'mcdonalds-canada', 'Egg BLT McMuffin with Shredded Lettuce (McDonald''s in Walmart)', 'Breakfast', 'This breakfast sandwich is made with a freshly cracked Canada Grade A egg, topped with crispy hickory smoked bacon (B), shredded lettuce (L) and fresh tomato (T), mayo-style sauce and a slice of processed cheese, served on a toasted English muffin. Only offered at McDonald’s in Walmart.', 13),
  ('chicken-mcmuffin', 'mcdonalds-canada', 'Chicken McMuffin', 'Breakfast', 'A breaded seasoned chicken patty, made with chicken raised on Canadian farms, with mayo- style sauce, a slice of tasty processed cheese sitting on a toasted English muffin.', 14),
  ('egg-mcmuffin', 'mcdonalds-canada', 'Egg McMuffin', 'Breakfast', 'Our signature breakfast sandwich boasts a freshly cracked Canada Grade A egg topped with Canadian bacon and a slice of tasty processed cheese, sitting happily on a toasted English muffin.', 15),
  ('sausage-n-egg-mcmuffin', 'mcdonalds-canada', 'Sausage ''N Egg McMuffin', 'Breakfast', 'The savoury taste of sausage, tasty processed cheese and a freshly cracked Canada Grade A egg add up to triple deliciousness on a toasty English muffin.', 16),
  ('bacon-n-egg-mcmuffin', 'mcdonalds-canada', 'Bacon ''N Egg McMuffin', 'Breakfast', 'Take your bacon and eggs the tasty way. Crispy hickory smoked bacon on a freshly cracked Canada Grade A egg. Topped with processed cheese, nestled comfortably in a toasty English muffin. Yum.', 17),
  ('sausage-mcmuffin', 'mcdonalds-canada', 'Sausage McMuffin', 'Breakfast', 'Wake up to delicious flavour with a big bite into savoury sausage and a slice of golden processed cheese held inside a toasted English muffin.', 18),
  ('plain-bagel-with-butter', 'mcdonalds-canada', 'Plain Bagel With Butter', 'Breakfast', 'Fall in love with one of our toasted plain bagels. Crispy on the outside, warm and chewy on the inside. Enjoy one toasted with butter today.', 19),
  ('everything-bagel-with-butter', 'mcdonalds-canada', 'Everything Bagel with Butter', 'Breakfast', 'Made with onion, garlic and sunflower seeds, topped with sesame seeds, poppy seeds and roasted onion. Enjoy one toasted with butter today. Not available in Quebec.', 20),
  ('sesame-seed-bagel-with-butter-qc-only', 'mcdonalds-canada', 'Sesame Bagel with Butter', 'Breakfast', 'A toasted bagel topped with sesame seeds, crispy on the outside, warm and tender on the inside. Enjoy one toasted with butter today.', 21),
  ('plain-bagel-with-plain-cream-cheese', 'mcdonalds-canada', 'Plain Bagel With Regular Cream Cheese Product', 'Breakfast', 'Fall in love with one of our plain bagels. Crispy on the outside, warm and chewy on the inside. Enjoy one toasted with regular cream cheese product today.', 22),
  ('everything-bagel-with-plain-cream-cheese', 'mcdonalds-canada', 'Everything Bagel With Regular Cream Cheese Product', 'Breakfast', 'Made with onion, garlic and sunflower seeds, topped with sesame seeds, poppy seeds and roasted onion. Enjoy one toasted with regular cream cheese product today. Not available in Quebec.', 23),
  ('sesame-seed-bagel-95g-with-plain-cream-cheese', 'mcdonalds-canada', 'Sesame Bagel With Regular Cream Cheese Product', 'Breakfast', 'A toasted bagel topped with sesame seeds, crispy on the outside, warm and tender on the inside. Enjoy one toasted with regular cream cheese product today.', 24),
  ('egg-blt-with-plain-bagel', 'mcdonalds-canada', 'Egg BLT Bagel with Plain Bagel', 'Breakfast', 'Made with a plain bagel, and topped with a freshly cracked Canada Grade A egg, hickory smoked bacon, sliced tomato and crisp lettuce.', 25),
  ('egg-blt-with-everything-bagel', 'mcdonalds-canada', 'Egg BLT Bagel with Everything Bagel', 'Breakfast', 'Made with an everything bagel, and topped with a freshly cracked Canada Grade A egg, hickory smoked bacon, sliced tomato and crisp lettuce. Not available in Quebec.', 26),
  ('egg-blt-with-sesame-seed-bagel', 'mcdonalds-canada', 'Sesame Egg BLT Bagel', 'Breakfast', 'Made with a sesame bagel, and topped with a freshly cracked Canada Grade A egg, hickory smoked bacon, sliced tomato and crisp lettuce.', 27),
  ('bacon-n-egg-with-plain-bagel', 'mcdonalds-canada', 'Bacon ‘N Egg Bagel with Plain Bagel', 'Breakfast', 'Enjoy a plain bagel, topped with hickory smoked bacon, a freshly cracked Canada Grade A egg and slice of processed cheese.', 28),
  ('bacon-n-egg-with-everything-bagel', 'mcdonalds-canada', 'Bacon ‘N Egg Bagel with Everything Bagel', 'Breakfast', 'Enjoy an everything bagel, topped with hickory smoked bacon, a freshly cracked Canada Grade A egg and slice of processed cheese. Not available in Quebec.', 29),
  ('bacon-n-egg-with-sesame-seed-bagel', 'mcdonalds-canada', 'Sesame Bacon ‘N Egg Bagel', 'Breakfast', 'Enjoy a sesame bagel, topped with hickory smoked bacon, a freshly cracked Canada Grade A egg and slice of processed cheese.', 30),
  ('sausage-n-egg-with-plain-bagel', 'mcdonalds-canada', 'Sausage ‘N Egg Bagel with Plain Bagel', 'Breakfast', 'Delicious sausage and a freshly cracked Canada Grade A egg with processed cheese, all in between a plain bagel.', 31),
  ('sausage-n-egg-with-everything-bagel', 'mcdonalds-canada', 'Sausage ‘N Egg Bagel with Everything Bagel', 'Breakfast', 'Delicious sausage and a freshly cracked Canada Grade A egg with processed cheese, all in between an everything bagel. Not available in Quebec.', 32),
  ('sausage-n-egg-with-sesame-seed-bagel', 'mcdonalds-canada', 'Sesame Sausage ‘N Egg Bagel', 'Breakfast', 'Delicious sausage and a freshly cracked Canada Grade A egg with processed cheese, all in between a sesame bagel.', 33),
  ('chicken-mcgriddles', 'mcdonalds-canada', 'Chicken McGriddles', 'Breakfast', 'A breaded seasoned chicken patty, made with chicken raised on Canadian farms, on two sweet, warm maple-flavoured griddle cakes.', 34),
  ('bacon-egg-cheese-mcgriddles', 'mcdonalds-canada', 'Bacon, Egg & Cheese McGriddles', 'Breakfast', 'Sizzling crispy hickory smoked bacon, a freshly cracked Canada Grade A egg and processed cheese piled up on two sweet, warm, maple-flavoured griddle cakes.', 35),
  ('sausage-egg-cheese-mcgriddles', 'mcdonalds-canada', 'Sausage Egg & Cheese McGriddles', 'Breakfast', 'Savoury sausage, a freshly cracked Canada Grade A egg and processed cheese piled up on two sweet, warm, maple-flavoured griddle cakes.', 36),
  ('sausage-mcgriddles', 'mcdonalds-canada', 'Sausage McGriddles', 'Breakfast', 'Savoury sausage piled up on two sweet, warm, maple-flavoured griddle cakes.', 37),
  ('breakfast-burrito', 'mcdonalds-canada', 'Breakfast Burrito', 'Breakfast', 'A savoury mix of fluffy eggs, tomatoes, green chilies, onions, sausage and processed cheese all wrapped in a warm white flour tortilla and served with salsa on the side.', 38),
  ('english-muffin-with-butter', 'mcdonalds-canada', 'English Muffin with Butter', 'Breakfast', 'Melted butter sitting happily on a toasted English muffin.', 39),
  ('hash-browns', 'mcdonalds-canada', 'Hash Browns', 'Breakfast', 'That crisp, flaky, fluffy-on-the-inside favourite. A perfect breakfast companion, and irresistible on its own.', 40),
  ('hotcakes-with-syrup-and-butter', 'mcdonalds-canada', 'Hotcakes with Syrup and Butter', 'Breakfast', 'Three golden-brown, melt-in-your-mouth hotcakes served with butter and tasty syrup on the side.', 41),
  ('hotcakes', 'mcdonalds-canada', 'Hotcakes', 'Breakfast', 'Start the day with three golden-brown, melt-in-your-mouth hotcakes.', 42),
  ('hockey-hero-burger', 'mcdonalds-canada', 'Hockey Hero Burger®', 'Beef', 'The Hockey Hero Burger® is back on the ice after a long break, with a fresh take. Made with three juicy 100% Canadian beef patties, shredded lettuce, crispy hickory-smoked bacon, processed cheese and mayo-style sauce on a toasted homestyle bun – one bite and you''ll know why it''s called the Hockey Hero Burger.', 43),
  ('cheeseburger-deluxe', 'mcdonalds-canada', 'Cheeseburger Deluxe', 'Beef', 'Your favourite cheeseburger is now made deluxe! A slice of processed cheese on a juicy, 100% Canadian beef patty with pickles and onions, ketchup, mustard, mayo style sauce, tomato, and shredded lettuce on a toasted bun.', 44),
  ('double-hamburger', 'mcdonalds-canada', 'Double Hamburger', 'Beef', 'Made with two juicy 100% Canadian beef patties, topped with pickles, onions, ketchup and mustard on a freshly toasted bun.', 45),
  ('big-mac-sandwich', 'mcdonalds-canada', 'Big Mac', 'Beef', 'Nothing compares to two 100% Canadian beef patties, special sauce, crisp lettuce, processed cheese, pickles and onions on a toasted sesame seed bun.', 46),
  ('double-big-mac-200946', 'mcdonalds-canada', 'The Big Mac-David - Double Big Mac', 'Beef', 'Four 100% Canadian beef patties, special sauce, crisp lettuce, processed cheese, pickles, and onions, all stacked on a toasted sesame seed bun. A bold burger that leads the way, just like #97 on the ice.', 47),
  ('hamburger', 'mcdonalds-canada', 'Hamburger', 'Beef', 'The comforting taste of the juicy and delicious 100% Canadian beef burger, topped with tangy pickles, ketchup, mustard and the sweet bite of onion, all on a freshly toasted bun. Just like you remember.', 48),
  ('mcdouble', 'mcdonalds-canada', 'McDouble', 'Beef', 'A slice of melted processed cheese between two 100% Canadian beef patties, topped with pickles, onions, ketchup and mustard on a toasted bun.', 49),
  ('cheeseburger', 'mcdonalds-canada', 'Cheeseburger', 'Beef', 'A slice of melted processed cheese on a juicy, 100% Canadian beef patty with tangy pickles and onions, ketchup and mustard on a freshly-toasted bun.', 50),
  ('double-cheeseburger', 'mcdonalds-canada', 'Double Cheeseburger', 'Beef', 'We make it like we always have: two slices of processed cheese with two 100% Canadian beef patties, pickles, onions, ketchup and mustard on a freshly toasted bun.', 51),
  ('quarter-pounder-with-cheese', 'mcdonalds-canada', 'Quarter Pounder with Cheese', 'Beef', 'A quarter pound* of 100% Canadian beef and two slices of melty processed cheese on a toasted sesame seed bun. Order today!

*Before cooking.', 52),
  ('quarter-pounder-without-cheese', 'mcdonalds-canada', 'Quarter Pounder without Cheese', 'Beef', 'A quarter pound* of 100% Canadian beef topped with tangy pickles, ketchup, mustard and the sweet bite of slivered onions, on a toasted sesame seed bun. Itâ€™s a simple recipe, but it works. *Weight before cooking at least 112.3g.', 53),
  ('double-quarter-pounder-with-cheese', 'mcdonalds-canada', 'Double Quarter Pounder with Cheese', 'Beef', 'Two quarter pound* 100% Canadian beef patties. Layered with two slices of melty cheese, slivered onions and pickles on sesame seed bun. *Weight  before cooking at least 112.3g .', 54),
  ('double-quarter-pounder-without-cheese', 'mcdonalds-canada', 'Double Quarter Pounder without Cheese', 'Beef', 'Two quarter pound* 100% Canadian beef patties layered with tangy pickles, ketchup, mustard and the sweet bite of slivered onions, on a toasted sesame seed bun. *Weight  before cooking at least 112.3g .', 55),
  ('quarter-pounder-blt', 'mcdonalds-canada', 'Quarter Pounder BLT', 'Beef', 'Sink your teeth into crisp bacon, juicy tomato and fresh lettuce to reach the beefy, cheesy core of the Quarter Pounder. Did we mention the bacon? Thereâ€™s bacon.', 56),
  ('double-quarter-pounder-blt', 'mcdonalds-canada', 'Double Quarter Pounder BLT', 'Beef', 'Two quarter pound* 100% Canadian beef patties. Layered with a slice of processed cheese, hickory-smoked bacon strips, fresh lettuce, tomato, slivered onions, mayo-style sauce, ketchup, mustard and pickles on a toasted sesame seed bun. 

*Weight before cooking at least 112.3g.', 57),
  ('chicken-big-mac', 'mcdonalds-canada', 'Chicken Big Mac', 'Chicken', 'It’s back! The Chicken Big Mac features two patties made with 100% Canadian-raised seasoned chicken breast in a crispy, light-tasting coating, along with the much-loved special sauce, lettuce, processed cheese and pickles. With a side of classic McDonald''s fries, we''d say this sounds like the perfect meal.', 58),
  ('franks-redhot-original-mccrispy', 'mcdonalds-canada', 'Frank’s RedHot® Original McCrispy', 'Chicken', 'We cranked up the flavour on the McCrispy with the added kick of Frank’s RedHot®. We took our McCrispy  chicken sandwich, made with tender and juicy 100% Canadian-raised seasoned chicken, and topped it with shredded lettuce, mayo-style sauce and Frank’s RedHot® Original Thick Sauce. Served on a potato bun.', 59),
  ('franks-redhot-original-mccrispy-bacon-deluxe', 'mcdonalds-canada', 'Frank’s RedHot® Original McCrispy Bacon Deluxe', 'Chicken', 'Hickory-smoked bacon and a slice of fresh tomato take the McCrispy to the next level. Made with crispy, tender and juicy 100% Canadian-raised seasoned chicken, then topped with shredded lettuce, creamy mayo-style sauce and Frank’s RedHot® Original Thick Sauce, and served on a soft potato bun.', 60),
  ('creamy-chipotle-chicken-mcwrap-crispy', 'mcdonalds-canada', 'Creamy Chipotle Chicken McWrap - Crispy', 'Chicken', 'Made with 100% Canadian-raised seasoned chicken topped with creamy chipotle sauce, crispy tri-colour tortilla strips, shredded lettuce, sliced tomato and cucumbers. All wrapped in a soft white flour tortilla.', 61),
  ('creamy-chipotle-chicken-mcwrap-grilled', 'mcdonalds-canada', 'Creamy Chipotle Chicken McWrap - Grilled', 'Chicken', 'Made with 100% Canadian-raised seasoned chicken topped with creamy chipotle sauce, crispy tri-colour tortilla strips, shredded lettuce, sliced tomato and cucumbers. All wrapped in a soft white flour tortilla.', 62),
  ('sweet-chili-junior-chicken', 'mcdonalds-canada', 'Sweet Chili Junior Chicken', 'Chicken', 'Your tastebuds will be singing a whole new tune with a remixed Sweet Chili Junior Chicken made with Canadian-raised crispy seasoned chicken, topped with crunchy shredded lettuce, tangy sweet chili sauce and mayo-style sauce, all on a toasty bun.', 63),
  ('mccrispy', 'mcdonalds-canada', 'McCrispy', 'Chicken', 'The McCrispy is a crispy chicken sandwich made with tender and juicy 100% Canadian-raised seasoned chicken. It’s topped with shredded lettuce and creamy mayo-style sauce and served on a soft potato bun for a taste that’s so McDonald’s.', 64),
  ('spicy-mccrispy', 'mcdonalds-canada', 'Spicy McCrispy', 'Chicken', 'The Spicy McCrispy is a crispy chicken sandwich topped with our signature habanero sauce. Made with tender and juicy 100% Canadian-raised seasoned chicken and served on a soft potato bun, it has a taste that’s unmistakably McDonald’s.', 65),
  ('spicy-mccrispy-bacon-deluxe', 'mcdonalds-canada', 'Spicy Bacon Deluxe McCrispy Sandwich', 'Chicken', 'The Spicy Bacon Deluxe McCrispy is big on everything, including heat. With our southern-style fried chicken patty on a soft potato bun, topped with shredded lettuce, hickory-smoked bacon, tomato and our spicy Habanero sauce, this sandwich kicks crispy, juicy and tender up to the next level.', 66),
  ('mccrispy-bacon-deluxe', 'mcdonalds-canada', 'McCrispy Bacon Deluxe', 'Chicken', 'Bacon and a slice of fresh tomato take the McCrispy to the next level. Made with crispy, tender and juicy 100% Canadian-raised seasoned chicken, then topped with shredded lettuce, creamy mayo-style sauce and served on a soft potato bun for a taste that’s so McDonald’s.', 67),
  ('mccrispy-with-grilled-chicken', 'mcdonalds-canada', 'Grilled Chicken Sandwich', 'Chicken', 'The Grilled Chicken Sandwich is made with tender and juicy 100% Canadian-raised grilled seasoned chicken. Topped with shredded lettuce, creamy mayo-style sauce and served on a soft potato bun for that McD’s flavour you crave.', 68),
  ('bacon-deluxe-mccrispy-sandwich-with-grilled-chicken', 'mcdonalds-canada', 'Bacon Deluxe Grilled Chicken Sandwich', 'Chicken', 'Bacon and a slice of fresh tomato take the Grilled Chicken Sandwich to the next level. Made with tender and juicy 100% Canadian-raised grilled seasoned chicken, then topped with shredded lettuce, creamy mayo-style sauce and served on a soft potato bun. This is big flavour in every bite.', 69),
  ('spicy-grilled-chicken-sandwich', 'mcdonalds-canada', 'Spicy Grilled Chicken Sandwich', 'Chicken', 'Made with tender and juicy 100% Canadian-raised grilled seasoned chicken, and topped with shredded lettuce and our signature Habanero sauce, it’s a spicy-lovers dream served on a soft potato bun.', 70),
  ('spicy-bacon-deluxe-grilled-chicken-sandwich', 'mcdonalds-canada', 'Spicy Bacon Deluxe Grilled Chicken Sandwich', 'Chicken', 'The Spicy Bacon Deluxe Grilled Chicken Sandwich is big on everything, including heat. Made with 100% Canadian-raised grilled seasoned chicken on a soft potato bun, topped with shredded lettuce, hickory-smoked bacon, tomato and our spicy Habanero sauce, this sandwich kicks juicy and tender up to the next level.', 71),
  ('habanero-mcchicken-sandwich', 'mcdonalds-canada', 'Spicy Habanero McChicken', 'Chicken', 'Our classic McChicken packed with a punch! This spicy Habanero McChickenÂ® is topped with our creamy Habanero sauce. Perfectly breaded seasoned chicken, crisp shredded lettuce, all on a freshly toasted sesame bun. Some ingredients are just meant to be together.', 72),
  ('mcchicken', 'mcdonalds-canada', 'McChicken', 'Chicken', 'Breaded seasoned chicken and crisp lettuce, topped with our Mayo-Style Sauce. Some ingredients are just meant to be together.', 73),
  ('junior-chicken', 'mcdonalds-canada', 'Junior Chicken', 'Chicken', 'You donâ€™t need to compromise with the great taste of a Junior Chicken sandwich, made with chicken raised on Canadian farms, at a price you can always feel good about.', 74),
  ('4-chicken-mcnuggets', 'mcdonalds-canada', '4 Chicken McNuggets', 'Chicken', 'No artificial flavours, colours or preservatives. Made with 100% seasoned chicken breast, the Chicken McNuggets you crave are still simply delicious.', 75),
  ('6-chicken-mcnuggets', 'mcdonalds-canada', '6 Chicken McNuggets', 'Chicken', 'No artificial flavours, colours or preservatives. Made with 100% seasoned chicken breast, the Chicken McNuggets you crave are still simply delicious.', 76),
  ('10-chicken-mcnuggets', 'mcdonalds-canada', '10 Chicken McNuggets', 'Chicken', 'No artificial flavours, colours or preservatives. Made with 100% seasoned chicken breast, the Chicken McNuggets you crave are still simply delicious.', 77),
  ('20-chicken-mcnuggets', 'mcdonalds-canada', '20 Chicken McNuggets (Serves 2)', 'Chicken', 'No artificial flavours, colours or preservatives. Made with 100% seasoned chicken breast, the Chicken McNuggets you crave are still simply delicious.', 78),
  ('spicy-buffalo-chicken-poutine', 'mcdonalds-canada', 'Spicy Buffalo Chicken Poutine (Québec)', 'Chicken', 'Made with our World Famous Fries layered with stringy cheese curds and savoury gravy and topped with crispy pieces of 100% Canadian raised seasoned chicken, drizzled with spicy buffalo sauced and topped with chopped green onions. Only offered in Quebec.', 79),
  ('happy-meal-snack-wrap-crispy', 'mcdonalds-canada', 'Chicken Snack Wrap Happy Meal with Crispy Chicken', 'Chicken', 'Made with 100% Canadian-raised seasoned chicken topped with shredded lettuce and mayo-style sauce wrapped in a soft white flour tortilla. Try one today with your choice of apple slices or mini/small fries, yogurt and small/child-size drink (as applicable).', 80),
  ('spicy-buffalo-snack-wrap-grilled', 'mcdonalds-canada', 'Spicy Buffalo Chicken Snack Wrap with Grilled Chicken', 'Chicken', 'Made with 100% Canadian raised seasoned chicken topped with shredded lettuce, shredded cheese and spicy buffalo sauce wrapped in a soft white flour tortilla.', 81),
  ('spicy-buffalo-snack-wrap-crispy', 'mcdonalds-canada', 'Spicy Buffalo Chicken Snack Wrap with Crispy Chicken', 'Chicken', 'Made with 100% Canadian raised seasoned chicken topped with shredded lettuce, shredded cheese and spicy buffalo sauce wrapped in a soft white flour tortilla.', 82),
  ('new-sweet-chili-mcwrap-grilled', 'mcdonalds-canada', 'Sweet Chili McWrap', 'Chicken', 'Made with 100% Canadian raised seasoned chicken topped with shredded lettuce, cucumbers, mayo-style sauce and sweet chili sauce. All wrapped up in a soft white flour tortilla.', 83),
  ('new-sweet-chili-mcwrap-crispy', 'mcdonalds-canada', 'Sweet Chili McWrap', 'Chicken', 'Made with 100% Canadian raised seasoned chicken topped with shredded lettuce, sliced tomato, cucumbers, mayo-style sauce and sweet chili sauce. All wrapped up in a soft white flour tortilla.', 84),
  ('new-chicken-and-bacon-mcwrap-crispy', 'mcdonalds-canada', 'Chicken & Bacon McWrap', 'Chicken', 'Made with 100% Canadian raised seasoned chicken topped with shredded lettuce, sliced tomato, cucumbers, hickory-smoked bacon and mayo-style sauce. All wrapped up in a soft white flour tortilla.', 85),
  ('new-chicken-and-bacon-mcwrap-grilled', 'mcdonalds-canada', 'Chicken & Bacon McWrap', 'Chicken', 'Made with 100% Canadian raised seasoned chicken topped with shredded lettuce, sliced tomato, cucumbers, hickory-smoked bacon and mayo-style sauce. All wrapped up in a soft white flour tortilla.', 86),
  ('ranch-chicken-snack-wrap-grilled-for-relaunch', 'mcdonalds-canada', 'Ranch Chicken Snack Wrap with Grilled Chicken', 'Chicken', 'Made with 100% Canadian raised seasoned chicken topped with shredded lettuce, shredded cheese and ranch sauce wrapped in a soft white flour tortilla.', 87),
  ('ranch-chicken-snack-wrap-crispy-for-relaunch', 'mcdonalds-canada', 'Ranch Chicken Snack Wrap with Crispy Chicken', 'Chicken', 'Made with 100% Canadian raised seasoned chicken topped with shredded lettuce, shredded cheese and ranch sauce wrapped in a soft white flour tortilla.', 88),
  ('franks-original-mcveggie', 'mcdonalds-canada', 'Frank’s RedHot® Original McVeggie', 'Sandwiches & Wraps', 'We cranked up the flavour on the McVeggie with the added kick of Frank’s RedHot®. A breaded veggie patty made with a blend of vegetables (including carrots, green beans, zucchini, peas, soybeans, broccoli and corn) and seasoning, topped with shredded lettuce, mayo-style sauce and Frank’s RedHot® Original Thick Sauce, served on a toasted sesame bun.', 89),
  ('mcveggie', 'mcdonalds-canada', 'McVeggie', 'Sandwiches & Wraps', 'A breaded veggie patty made with a blend of vegetables (including carrots, green beans, zucchini, peas, soybeans, broccoli and corn) and seasoning, topped with shredded lettuce and creamy mayo-style sauce, served on a toasted sesame bun.', 90),
  ('spicy-mcveggie', 'mcdonalds-canada', 'Spicy McVeggie', 'Sandwiches & Wraps', 'A breaded veggie patty made with a blend of vegetables (including carrots, green beans, zucchini, peas, soybeans, broccoli and corn) and seasoning, topped with shredded lettuce and creamy Habanero sauce, served on a toasted sesame bun.', 91),
  ('filet-o-fish', 'mcdonalds-canada', 'Filet-O-Fish', 'Sandwiches & Wraps', 'Dive right in. Our Filet-O-Fish is pure temptation on a lightly steamed bun, topped with processed cheese and tangy tartar sauce.', 92),
  ('double-filet-o-fish', 'mcdonalds-canada', 'Double Filet-O-Fish', 'Sandwiches & Wraps', 'Bite into not one, but two crisp and flaky white fish filets. Topped with processed cheese and tangy tartar sauce, it’s double the delicious on a warm steamed bun.', 93),
  ('happy-meal-snack-wrap-grilled', 'mcdonalds-canada', 'Chicken Snack Wrap Happy Meal with Grilled Chicken', 'Sandwiches & Wraps', 'Made with 100% Canadian-raised seasoned chicken topped with shredded lettuce and mayo-style sauce wrapped in a soft white flour tortilla. Try one today with your choice of apple slices or mini/small fries, yogurt and small/child-size drink (as applicable).', 94),
  ('Baked-Blueberry-Cream-Cheese-Pie', 'mcdonalds-canada', 'Baked Blueberry Cream Cheese  Pie', 'Snacks & Sides', 'Made with blueberries and a sweet cream cheese filling wrapped in a flaky crust, baked fresh daily and served warm.', 95),
  ('chewy-chocolate-chunk-cookie', 'mcdonalds-canada', 'Chewy Chocolate Chunk Cookie', 'Snacks & Sides', 'A classic chewy, soft-baked cookie made with decadent chocolate chunks.', 96),
  ('rainbow-sprinkle-cookie', 'mcdonalds-canada', 'Rainbow Sprinkle Cookie', 'Snacks & Sides', 'A soft-baked cookie bursting with sprinkles and sweet white confectionary pieces.', 97),
  ('toasted-smores-cookie', 'mcdonalds-canada', 'Toasted S’mores Cookie', 'Snacks & Sides', 'Enjoy the cozy flavour of this soft-baked cookie loaded with marshmallows, chocolate chips and graham-style pieces.', 98),
  ('chocolate-chip-muffin', 'mcdonalds-canada', 'Chocolate Chip Muffin', 'Snacks & Sides', 'Baked fresh daily, the Chocolate Chip Muffin is sweet and delicious, mixed with milk chocolate chips and topped with more milk chocolate chips.', 99),
  ('apple-slices', 'mcdonalds-canada', 'Apple Slices', 'Snacks & Sides', 'A crisp and delicious snack, prepared for fruit lovers on the go.', 100),
  ('french-fries-medium', 'mcdonalds-canada', 'World Famous Fries', 'Snacks & Sides', 'McDonaldâ€™s World Famous Fries are always a delicious choice. Cut from whole potatoes grown on Canadian farms, our fries are cooked to golden perfection in a vegetable oil blend. Mmmmâ€¦ of course you want fries with that!', 101),
  ('mini-fry', 'mcdonalds-canada', 'Mini Fry', 'Snacks & Sides', 'World famous fries in a mini size! Cut from whole potatoes grown on Canadian farms, our fries are cooked to golden perfection in a vegetable oil blend. Visit today!', 102),
  ('poutine', 'mcdonalds-canada', 'Poutine', 'Snacks & Sides', 'Rich and tasty gravy? Melty, mouth-watering cheese curds? On our World Famous Fries? You better believe it!', 103),
  ('fruit-fibre-muffin', 'mcdonalds-canada', 'Fruit & Fibre Muffin', 'Snacks & Sides', 'A perfect companion to coffee; a quick-and-easy mid-morning or afternoon treat. With a choice of five delectable flavours including Banana Chocolate Chunk, Blueberry, Carrot, Fruit â€˜n Fibre and Cranberry Orange. Enjoy one today!', 104),
  ('blueberry-muffin', 'mcdonalds-canada', 'Blueberry Muffin', 'Snacks & Sides', 'A perfect companion to coffee; a quick-and-easy mid-morning or afternoon treat. With a choice of five delectable flavours including Banana Chocolate Chunk, Blueberry, Carrot, Fruit â€˜n Fibre and Cranberry Orange. Enjoy one today!', 105),
  ('carrot-muffin', 'mcdonalds-canada', 'Carrot Muffin', 'Snacks & Sides', 'A perfect companion to coffee; a quick-and-easy mid-morning or afternoon treat. With a choice of five delectable flavours including Banana Chocolate Chunk, Blueberry, Carrot, Fruit â€˜n Fibre and Cranberry Orange. Enjoy one today!', 106),
  ('cranberry-orange-muffin-201057', 'mcdonalds-canada', 'Cranberry Orange Muffin', 'Snacks & Sides', 'A perfect companion to coffee; a quick-and-easy mid-morning or afternoon treat. With a choice of five delectable flavours including Banana Chocolate Chunk, Blueberry, Carrot, Fruit â€˜n Fibre and Cranberry Orange. Enjoy one today!', 107),
  ('baked-apple-pie', 'mcdonalds-canada', 'Baked Apple Pie', 'Snacks & Sides', 'Itâ€™s the tradition you love to uphold, with delicious apples lightly spiced with cinnamon in a flaky crust, baked fresh daily.', 108),
  ('cadbury-creme-egg-mcflurry-regular', 'mcdonalds-canada', 'Cadbury Creme Egg McFlurry', 'Desserts & Shakes', 'Smooth vanilla soft serve blended with pieces of milk chocolate then swirled together with the delicious flavour of sweet Cadbury Creme Egg® fondant all whipped together for a decadent cool and creamy dessert.', 109),
  ('triple-thick-shamrock-shake-syrup-medium', 'mcdonalds-canada', 'Shamrock Shake', 'Desserts & Shakes', 'A classic flavour is back for a limited time only! The delicious and refreshing taste of mint is back in our iconic Shamrock Shake®.', 110),
  ('salted-caramel-mcFlurry-regular', 'mcdonalds-canada', 'Salted Caramel McFlurry', 'Desserts & Shakes', 'Unwrap a new favourite McFlurry flavour this holiday season, with caramel sauce and a crunchy salted caramel topping, swirled into smooth vanilla soft serve.', 111),
  ('sundae-strawberry', 'mcdonalds-canada', 'Strawberry Sundae', 'Desserts & Shakes', 'Smooth and creamy vanilla soft serve, topped with strawberry sauce.', 112),
  ('cone-vanilla', 'mcdonalds-canada', 'Vanilla Cone', 'Desserts & Shakes', 'Make time for a moment of sweetness with creamy vanilla soft served in a crispy cone.', 113),
  ('sundae-hot-fudge', 'mcdonalds-canada', 'Hot Fudge Sundae', 'Desserts & Shakes', 'Smooth and creamy vanilla soft serve, topped with decadent hot fudge sauce. Mmmm!', 114),
  ('sundae-hot-caramel', 'mcdonalds-canada', 'Hot Caramel Sundae', 'Desserts & Shakes', 'Smooth and creamy vanilla soft serve, topped with your choice of yummy caramel sauce. Mmmm!', 115),
  ('mcflurry-oreo-regular-size-portion', 'mcdonalds-canada', 'Oreo McFlurry', 'Desserts & Shakes', 'Deliciousness starts with creamy vanilla soft serve swirled together with crunchy Oreo cookies. Walk in to your nearest McDonald’s and enjoy the yummy taste. Order today!', 116),
  ('mcflurry-dessert-crushed-skor-candy-bars-regular-size-portion', 'mcdonalds-canada', 'SKOR McFlurry', 'Desserts & Shakes', 'Deliciousness starts with creamy vanilla soft serve swirled together with pieces of SKOR bar. Walk in to your nearest McDonald’s and enjoy the yummy taste. Order today!
<br>
<br>
<b>SKOR® ALLERGY ALERT: Contains ALMONDS. View Ingredients and Allergens for full information.</b>', 117),
  ('smarties-mcflurry-regular-size-portion', 'mcdonalds-canada', 'Smarties McFlurry', 'Desserts & Shakes', 'Delicious starts with creamy vanilla soft serve swirled together with crushed Smarties. No artificial colours or flavours.', 118),
  ('triple-thick-milkshake-chocolate-medium', 'mcdonalds-canada', 'Chocolate Triple Thick Milkshake', 'Desserts & Shakes', 'Thick, smooth, and deliciously creamy soft serve, mixed with your choice of decadent chocolate, strawberry, or vanilla flavoured syrup for an extra taste of yumminess.', 119),
  ('triple-thick-milkshake-vanilla-medium', 'mcdonalds-canada', 'Vanilla Triple Thick Milkshake', 'Desserts & Shakes', 'Thick, smooth, and deliciously creamy soft serve, mixed with your choice of decadent chocolate, strawberry, or vanilla flavoured syrup for an extra taste of yumminess.', 120),
  ('triple-thick-milkshake-strawberry-medium', 'mcdonalds-canada', 'Strawberry Triple Thick Milkshake', 'Desserts & Shakes', 'Thick, smooth, and deliciously creamy soft serve, mixed with your choice of decadent chocolate, strawberry, or vanilla flavoured syrup for an extra taste of yumminess.', 121),
  ('strawberry-flavoured-yogurt-tube', 'mcdonalds-canada', 'Yogurt Tube', 'Desserts & Shakes', '', 122),
  ('nite-sprite-medium', 'mcdonalds-canada', 'Nite Sprite® - Medium', 'Beverages', 'Get the great taste of crisp Sprite® mixed with a blue raspberry flavoured syrup.', 123),
  ('strawberry-banana-smoothie-with-yogurt-medium', 'mcdonalds-canada', 'Strawberry Banana Real Fruit Smoothie', 'Beverages', 'Get a taste of real strawberry and banana purÃ©e blended to perfection with ice. Enjoy it with or without yogurt in small, medium and large', 124),
  ('blueberry-pomegranate-smoothie-with-yogurt-medium', 'mcdonalds-canada', 'Blueberry Pomegranate Real Fruit Smoothie', 'Beverages', 'Made with real fruit purée and ice, it’s a refreshing way to enjoy the taste of blueberries and pomegranate. Try yours with or without yogurt.', 125),
  ('mango-pineapple-smoothie-with-yogurt-medium', 'mcdonalds-canada', 'Mango Pineapple Real Fruit Smoothie', 'Beverages', 'Blended with ice, real mango and pineapple purée. Enjoy it with or without yogurt.', 126),
  ('watermelon-lime-fruit-splash-medium', 'mcdonalds-canada', 'Watermelon Lime Fruit Splash', 'Beverages', 'A refreshing lemonade beverage made with real lemon juice concentrate and real lemon pulp, with the sweet and tangy taste of watermelon and lime. Served over ice.', 127),
  ('lemon-fruit-splash-medium', 'mcdonalds-canada', 'Lemon Fruit Splash', 'Beverages', 'A refreshing lemonade beverage made with real lemon juice concentrate and real lemon pulp. Served over ice.', 128),
  ('fuze-iced-tea-medium', 'mcdonalds-canada', 'Fuze Iced Tea', 'Beverages', 'A refreshing blend of real tea and natural lemon flavour, served ice cold.', 129),
  ('fruitopia-strawberry-passion-awareness-medium', 'mcdonalds-canada', 'Fruitopia Strawberry Passion Awareness', 'Beverages', 'Real fruit beverage with added vitamin C, no artificial flavours and no caffeine.', 130),
  ('fruitopia-orange-groove-medium', 'mcdonalds-canada', 'Fruitopia Orange Groove', 'Beverages', 'Real fruit beverage with added vitamin C, no artificial flavours and no caffeine', 131),
  ('coca-cola-zero-medium', 'mcdonalds-canada', 'Coca-Cola Zero', 'Beverages', 'Real Coca-Cola taste with zero calories and zero sugar. Perfection on ice.', 132),
  ('coca-cola-medium', 'mcdonalds-canada', 'Coca-Cola', 'Beverages', 'Enjoy your favourite McDonald''s meal with a Coke. The original, refreshing ice-cold cola that goes well with your meal and completes the experience. Learn more!', 133),
  ('diet-coke-medium', 'mcdonalds-canada', 'Diet Coke', 'Beverages', 'Enjoy your favourite McDonald''s meal with a Diet Coke. A refreshing ice cold cola with a light taste that goes well with your meal and completes the experience. Learn more!', 134),
  ('orange-juice-medium', 'mcdonalds-canada', 'Minute Maid Orange Juice*', 'Beverages', 'Start your day with the goodness of pure orange juice*. No preservatives. No sugar added. An excellent source of vitamin C. *From concentrate.', 135),
  ('apple-juice-medium', 'mcdonalds-canada', 'Minute Maid Apple Juice*', 'Beverages', 'Enjoy the goodness of pure apple juice*.   No preservatives. No sugar added. An excellent source of vitamin C.*From concentrate. Apple juice enriched with vitamin C.', 136),
  ('1-partly-skimmed-milk-250-ml', 'mcdonalds-canada', '1% Partly Skimmed Milk - 250 ml', 'Beverages', 'Wholesome, delicious, low fat milk; a source of Vitamin A and an excellent source of calcium. Available in 1% chocolate milk too!', 137),
  ('1-partly-skimmed-chocolate-milk', 'mcdonalds-canada', '1% Partly Skimmed Chocolate Milk - 250 ml', 'Beverages', 'Wholesome, delicious, low fat chocolate milk; a source of Vitamin A and an excellent source of calcium. Available in 1% milk too!', 138),
  ('barqs-root-beer-medium', 'mcdonalds-canada', 'Barq''s Root Beer', 'Beverages', 'Get a tasty kick from every sip of ice cold Barqâ€™s.', 139),
  ('sprite-medium', 'mcdonalds-canada', 'Sprite', 'Beverages', 'The great taste of crisp, clear, Sprite. Made with 100% natural lemon-lime flavours, with no colours and no caffeine.', 140),
  ('dasani-water', 'mcdonalds-canada', 'Dasani Water', 'Beverages', 'Quench your thirst with a bottle of cool and refreshing Dasani water. Add a bottle to your meal order today!', 141),
  ('salted-caramel-latte-medium', 'mcdonalds-canada', 'Salted Caramel Latte', 'McCafé & Bakery', 'Treat yourself with the smooth and creamy Salted Caramel Latte, made with our signature McCafé espresso and topped with fresh Canadian milk, steamed and frothed. Visit today!', 142),
  ('salted-caramel-iced-coffee-medium', 'mcdonalds-canada', 'Salted Caramel Iced Coffee', 'McCafé & Bakery', 'Cool and refreshing, Premium Roast Coffee on ice, brewed from 100% Arabica beans, and made for you with your choice of 2% milk or cream. To suit your taste buds, choose between: regular, French Vanilla, Sugar-Free Vanilla or Salted Caramel.', 143),
  ('oat-iced-coffee-medium', 'mcdonalds-canada', 'McCafé Premium Roast Brewed Oat Iced Coffee', 'McCafé & Bakery', 'Cool and refreshing, Premium Roast Coffee on ice, brewed from 100% Arabica beans, and made for you with smooth and creamy oat beverage.', 144),
  ('berry-mcpops', 'mcdonalds-canada', 'Berry McPops', 'McCafé & Bakery', 'Mini pink powdered donut with a berries and cherry filling.', 145),
  ('white-chocolate-mcpops', 'mcdonalds-canada', 'White Chocolate McPops', 'McCafé & Bakery', 'Mini powdered donut with white chocolate filling.', 146),
  ('hazelnut-cocoa-mcpops', 'mcdonalds-canada', 'Hazelnut & Cocoa McPops', 'McCafé & Bakery', 'Mini donut with hazelnut filling, dusted with cocoa powder.', 147),
  ('coffee-medium', 'mcdonalds-canada', 'Premium Roast Brewed Coffee', 'McCafé & Bakery', 'Brewed from 100% Arabica beans, fire-roasted for a rich, delicious full-bodied flavour â€“ in your choice of regular or decaf.', 148),
  ('premium-tea-medium', 'mcdonalds-canada', 'Premium Tea', 'McCafé & Bakery', 'Relax. It’s your time to enjoy a long, slow sip of delicious and delectable tea. Choose from Orange Pekoe, Earl Grey, Peppermint or Green Tea – and enjoy.', 149),
  ('cappuccino-with-2-milk-medium', 'mcdonalds-canada', 'Cappuccino - 2% milk', 'McCafé & Bakery', 'Our Cappuccino is bold and classic, made with our signature McCafÃ© espresso topped with fresh Canadian milk, steamed and frothed.', 150),
  ('latte-with-2-milk-medium', 'mcdonalds-canada', 'Latte - 2% milk', 'McCafé & Bakery', 'Treat yourself with the smooth and sophisticated Latte, made with our signature McCafÃ© espresso and topped with fresh Canadian milk, steamed and frothed. Visit today!', 151),
  ('french-vanilla-latte-with-2-milk-medium', 'mcdonalds-canada', 'French Vanilla Latte', 'McCafé & Bakery', 'Treat yourself with the smooth and creamy French Vanilla Latte, made with our signature McCafÃ© espresso and topped with fresh Canadian milk, steamed and frothed. Visit today!', 152),
  ('latte-with-sugar-free-syrup-with-2-milk-medium', 'mcdonalds-canada', 'Latte with Sugar Free Syrup - 2% milk', 'McCafé & Bakery', 'Enjoy our Latte with Sugar Free syrup, made with our signature McCafÃ© espresso and topped with fresh Canadian milk, steamed and frothed. Try one at McDonaldâ€™s!', 153),
  ('caramel-latte-with-2-milk-medium', 'mcdonalds-canada', 'Caramel Latte - 2% milk', 'McCafé & Bakery', 'Our Latte is smooth and sophisticated, made with our signature  McCafÃ© espresso and topped with fresh Canadian milk, steamed and frothed. When youâ€™re in the mood for something special, add your choice of a French vanilla, sugar-free vanilla, or caramel flavour shot.', 154),
  ('mocha-with-2-milk-medium', 'mcdonalds-canada', 'Mocha', 'McCafé & Bakery', 'Made with 100% ethically sourced Arabica bean espresso, fresh milk, steamed and frothed, real whipped cream and chocolate syrup with a perfect balance of sweetness, vanilla and chocolate. Made with no artificial colours or flavours.', 155),
  ('espresso', 'mcdonalds-canada', 'Espresso', 'McCafé & Bakery', 'Get ready for a McCafÃ© Espresso â€“ a bold boost of rich flavour from our freshly ground espresso, made from 100% Arabica beans.', 156),
  ('double-espresso', 'mcdonalds-canada', 'Double Espresso', 'McCafé & Bakery', 'Get ready for a McCafÃ© Espresso â€“ a bold boost of rich flavour from our freshly ground espresso, made from 100% Arabica beans.', 157),
  ('americano-medium', 'mcdonalds-canada', 'Americano', 'McCafé & Bakery', 'Our Americano is bold and robust, made with our signature McCafÃ©  espresso combined with hot water, for coffee aficionados who prefer a bolder cup.', 158),
  ('hot-chocolate-with-2-milk-medium', 'mcdonalds-canada', 'Hot Chocolate', 'McCafé & Bakery', 'A hot chocolate made with a perfect balance of sweetness, vanilla, chocolate and steamed milk. Made with no artificial colours or flavours.', 159),
  ('higgins-burke-hot-chocolate', 'mcdonalds-canada', 'Higgins & Burke Hot Chocolate', 'McCafé & Bakery', '', 160),
  ('iced-coffee-medium', 'mcdonalds-canada', 'Premium Roast Brewed Iced Coffee', 'McCafé & Bakery', 'Cool and refreshing, premium roast coffee on ice, brewed from 100% Arabica beans, and made for you with your choice of 2% milk or cream. To suit your taste buds, choose between: regular, vanilla, sugar-free vanilla or caramel.', 161),
  ('vanilla-iced-coffee-medium', 'mcdonalds-canada', 'French Vanilla Iced Coffee', 'McCafé & Bakery', 'Cool and refreshing, Premium Roast Coffee on ice, brewed from 100% Arabica beans, and made for you with your choice of 2% milk or cream. To suit your taste buds, choose between: regular, French Vanilla, Sugar-Free Vanilla or Salted Caramel.', 162),
  ('caramel-iced-coffee-medium', 'mcdonalds-canada', 'Caramel Iced Coffee', 'McCafé & Bakery', 'Made from McCafÃ© top roast coffee, for the same rich creamy and delicious taste. Enjoy it as you like, with cream milk, black or sweet.', 163),
  ('coffee-iced-frapp-medium', 'mcdonalds-canada', 'Coffee Frappé', 'McCafé & Bakery', 'Coffee Frappé is made with the great taste of 100% Arabica beans in a creamy dairy base, freshly blended with ice for a deep, down cool and sweet creamy taste consistent from first sip to last. Made with no artificial flavours or colours.', 164),
  ('iced-coffee-with-sugar-free-syrup-medium', 'mcdonalds-canada', 'Iced Coffee with Sugar Free syrup', 'McCafé & Bakery', 'Cool and refreshing, Premium Roast Coffee on ice, brewed from 100% Arabica beans, and made for you with your choice of 2% milk or cream. Try it with a flavour shot; choose from vanilla, sugar free syrup or caramel.', 165),
  ('vanilla-chai-iced-frapp-small', 'mcdonalds-canada', 'McCafé Vanilla Chai Frappé', 'McCafé & Bakery', 'McCafé® Vanilla Chai Iced Frappé is made with the refreshingly exotic combination of vanilla and chai flavours, including cinnamon and nutmeg, in a creamy dairy base, freshly blended with ice for a balanced deep, down cool, consistent from first sip to last. Made with no artificial flavours or colours.', 166),
  ('chocolate-brownie-muffin', 'mcdonalds-canada', 'Chocolate Brownie Muffin', 'McCafé & Bakery', 'Baked fresh daily and moist like a brownie, with the decadent taste of chocolate mixed with sweet chocolate chips and topped with crunchy brownie pieces.', 167),
  ('french-fries-small-mcpicks', 'mcdonalds-canada', 'World Famous Fries – Small', 'McPicks', 'McDonald’s World Famous Fries are always a delicious choice. Cut from whole potatoes grown on Canadian farms, our fries are cooked to golden perfection in a vegetable oil blend. Mmmm… of course you want fries with that!', 168),
  ('banana-chocolate-chunk-muffin', 'mcdonalds-canada', 'Banana Chocolate Chunk Muffin', 'McPicks', 'A perfect companion to coffee; a quick-and-easy mid-morning or afternoon treat.  With a choice of five delectable flavours including Banana Chocolate Chunk, Blueberry, Carrot, Fruit â€˜n Fibre and Cranberry Orange.  Enjoy one today!', 169),
  ('baked-apple-pie-200553', 'mcdonalds-canada', '2 Baked Apple Pies', 'McPicks', 'Twice the enjoyment, with two Baked Apple Pies! It''s the tradition you love to uphold, with delicious apples lightly spiced with cinnamon in a flaky crust, baked fresh daily.', 170)
;

insert into menu_item_ingredients (menu_item_id, ingredient_id) values
  ('1-partly-skimmed-chocolate-milk', '1-partly-skimmed-chocolate-milk'),
  ('1-partly-skimmed-milk-250-ml', '1-partly-skimmed-milk'),
  ('10-chicken-mcnuggets', 'chicken-mcnuggets'),
  ('20-chicken-mcnuggets', 'chicken-mcnuggets'),
  ('4-chicken-mcnuggets', 'chicken-mcnuggets'),
  ('6-chicken-mcnuggets', 'chicken-mcnuggets'),
  ('Baked-Blueberry-Cream-Cheese-Pie', 'blueberry-cream-cheese-pie'),
  ('americano-medium', 'espresso-coffee'),
  ('americano-medium', 'water'),
  ('apple-juice-medium', 'apple-juice'),
  ('apple-slices', 'apple-slices'),
  ('bacon-deluxe-mccrispy-sandwich-with-grilled-chicken', 'bacon-slice'),
  ('bacon-deluxe-mccrispy-sandwich-with-grilled-chicken', 'grilled-chicken-portion'),
  ('bacon-deluxe-mccrispy-sandwich-with-grilled-chicken', 'lettuce'),
  ('bacon-deluxe-mccrispy-sandwich-with-grilled-chicken', 'mayonnaise-style-sauce'),
  ('bacon-deluxe-mccrispy-sandwich-with-grilled-chicken', 'potato-bun'),
  ('bacon-deluxe-mccrispy-sandwich-with-grilled-chicken', 'tomato-slice'),
  ('bacon-egg-cheese-mcgriddles', 'bacon-slice'),
  ('bacon-egg-cheese-mcgriddles', 'egg'),
  ('bacon-egg-cheese-mcgriddles', 'mcgriddles-cakes'),
  ('bacon-egg-cheese-mcgriddles', 'processed-cheese'),
  ('bacon-n-egg-mcmuffin', 'bacon-slice'),
  ('bacon-n-egg-mcmuffin', 'butter'),
  ('bacon-n-egg-mcmuffin', 'egg'),
  ('bacon-n-egg-mcmuffin', 'english-muffin'),
  ('bacon-n-egg-mcmuffin', 'processed-cheese'),
  ('bacon-n-egg-with-everything-bagel', 'bacon-slice'),
  ('bacon-n-egg-with-everything-bagel', 'butter'),
  ('bacon-n-egg-with-everything-bagel', 'egg'),
  ('bacon-n-egg-with-everything-bagel', 'everything-bagel'),
  ('bacon-n-egg-with-everything-bagel', 'processed-cheese'),
  ('bacon-n-egg-with-plain-bagel', 'bacon-slice'),
  ('bacon-n-egg-with-plain-bagel', 'butter'),
  ('bacon-n-egg-with-plain-bagel', 'egg'),
  ('bacon-n-egg-with-plain-bagel', 'processed-cheese'),
  ('bacon-n-egg-with-plain-bagel', 'regular-bagel'),
  ('bacon-n-egg-with-sesame-seed-bagel', 'bacon-slice'),
  ('bacon-n-egg-with-sesame-seed-bagel', 'butter'),
  ('bacon-n-egg-with-sesame-seed-bagel', 'egg'),
  ('bacon-n-egg-with-sesame-seed-bagel', 'processed-cheese'),
  ('bacon-n-egg-with-sesame-seed-bagel', 'sesame-seed-bagel'),
  ('baked-apple-pie', 'baked-apple-pie'),
  ('baked-apple-pie-200553', 'baked-apple-pie'),
  ('banana-chocolate-chunk-muffin', 'banana-chocolate-chunk-muffin'),
  ('barqs-root-beer-medium', 'barq-s-root-beer'),
  ('barqs-root-beer-medium', 'ice'),
  ('berry-mcpops', 'berry-mcpops-donut'),
  ('big-mac-sandwich', 'beef-patty'),
  ('big-mac-sandwich', 'big-mac-bun'),
  ('big-mac-sandwich', 'big-mac-sauce'),
  ('big-mac-sandwich', 'grill-seasoning'),
  ('big-mac-sandwich', 'lettuce'),
  ('big-mac-sandwich', 'onions-dehydrated'),
  ('big-mac-sandwich', 'pickle-slices'),
  ('big-mac-sandwich', 'processed-cheese'),
  ('blueberry-muffin', 'blueberry-muffin'),
  ('blueberry-pomegranate-smoothie-with-yogurt-medium', 'blueberry-pomegranate-smoothie-fruit-base'),
  ('blueberry-pomegranate-smoothie-with-yogurt-medium', 'ice'),
  ('blueberry-pomegranate-smoothie-with-yogurt-medium', 'smoothie-yogurt-mix'),
  ('breakfast-burrito', 'egg-mixture'),
  ('breakfast-burrito', 'processed-cheese'),
  ('breakfast-burrito', 'white-flour-tortilla'),
  ('cadbury-creme-egg-mcflurry-regular', 'cadbury-chocolate'),
  ('cadbury-creme-egg-mcflurry-regular', 'creme-egg-syrup'),
  ('cadbury-creme-egg-mcflurry-regular', 'vanilla-ice-milk'),
  ('cappuccino-with-2-milk-medium', '2-milk'),
  ('cappuccino-with-2-milk-medium', 'espresso-coffee'),
  ('caramel-iced-coffee-medium', '18-cream'),
  ('caramel-iced-coffee-medium', 'brewed-coffee'),
  ('caramel-iced-coffee-medium', 'caramel-flavoured-syrup'),
  ('caramel-latte-with-2-milk-medium', '2-milk'),
  ('caramel-latte-with-2-milk-medium', 'caramel-flavoured-syrup'),
  ('caramel-latte-with-2-milk-medium', 'espresso-coffee'),
  ('carrot-muffin', 'carrot-muffin'),
  ('cheeseburger', 'beef-patty'),
  ('cheeseburger', 'grill-seasoning'),
  ('cheeseburger', 'ketchup'),
  ('cheeseburger', 'mustard'),
  ('cheeseburger', 'onions-dehydrated'),
  ('cheeseburger', 'pickle-slices'),
  ('cheeseburger', 'processed-cheese'),
  ('cheeseburger', 'regular-bun'),
  ('cheeseburger-deluxe', 'beef-patty'),
  ('cheeseburger-deluxe', 'grill-seasoning'),
  ('cheeseburger-deluxe', 'ketchup'),
  ('cheeseburger-deluxe', 'lettuce'),
  ('cheeseburger-deluxe', 'mayonnaise-style-sauce'),
  ('cheeseburger-deluxe', 'mustard'),
  ('cheeseburger-deluxe', 'onions-dehydrated'),
  ('cheeseburger-deluxe', 'pickle-slices'),
  ('cheeseburger-deluxe', 'processed-cheese'),
  ('cheeseburger-deluxe', 'regular-bun'),
  ('cheeseburger-deluxe', 'tomato-slice'),
  ('chewy-chocolate-chunk-cookie', 'chocolate-chunk-cookie'),
  ('chicken-big-mac', 'big-mac-bun'),
  ('chicken-big-mac', 'big-mac-sauce'),
  ('chicken-big-mac', 'chicken-big-mac-patty'),
  ('chicken-big-mac', 'lettuce'),
  ('chicken-big-mac', 'pickle-slices'),
  ('chicken-big-mac', 'processed-cheese'),
  ('chicken-hash-brown-breakfast-wrap', 'hashbrowns'),
  ('chicken-hash-brown-breakfast-wrap', 'junior-chicken-patty'),
  ('chicken-hash-brown-breakfast-wrap', 'lettuce'),
  ('chicken-hash-brown-breakfast-wrap', 'mayonnaise-style-sauce'),
  ('chicken-hash-brown-breakfast-wrap', 'processed-cheese'),
  ('chicken-hash-brown-breakfast-wrap', 'white-flour-tortilla'),
  ('chicken-mcgriddles', 'junior-chicken-patty'),
  ('chicken-mcgriddles', 'mcgriddles-cakes'),
  ('chicken-mcmuffin', 'butter'),
  ('chicken-mcmuffin', 'english-muffin'),
  ('chicken-mcmuffin', 'junior-chicken-patty'),
  ('chicken-mcmuffin', 'mayonnaise-style-sauce'),
  ('chicken-mcmuffin', 'processed-cheese'),
  ('chocolate-brownie-muffin', 'chocolate-brownie-muffin-mix'),
  ('chocolate-chip-muffin', 'chocolate-chip-muffin'),
  ('coca-cola-medium', 'coca-cola'),
  ('coca-cola-medium', 'ice'),
  ('coca-cola-zero-medium', 'coca-cola-zero'),
  ('coca-cola-zero-medium', 'ice'),
  ('coffee-iced-frapp-medium', 'coffee-frappe'),
  ('coffee-iced-frapp-medium', 'ice'),
  ('coffee-medium', 'brewed-coffee'),
  ('cone-vanilla', 'large-cone'),
  ('cone-vanilla', 'vanilla-ice-milk'),
  ('cranberry-orange-muffin-201057', 'cranberry-orange-muffin'),
  ('creamy-chipotle-chicken-mcwrap-crispy', 'creamy-chipotle-sauce'),
  ('creamy-chipotle-chicken-mcwrap-crispy', 'crispy-chicken-patty'),
  ('creamy-chipotle-chicken-mcwrap-crispy', 'cucumber'),
  ('creamy-chipotle-chicken-mcwrap-crispy', 'lettuce'),
  ('creamy-chipotle-chicken-mcwrap-crispy', 'tomato-slice'),
  ('creamy-chipotle-chicken-mcwrap-crispy', 'tri-colour-tortilla-strips'),
  ('creamy-chipotle-chicken-mcwrap-crispy', 'white-flour-tortilla'),
  ('creamy-chipotle-chicken-mcwrap-grilled', 'creamy-chipotle-sauce'),
  ('creamy-chipotle-chicken-mcwrap-grilled', 'cucumber'),
  ('creamy-chipotle-chicken-mcwrap-grilled', 'grilled-chicken-portion'),
  ('creamy-chipotle-chicken-mcwrap-grilled', 'lettuce'),
  ('creamy-chipotle-chicken-mcwrap-grilled', 'tomato-slice'),
  ('creamy-chipotle-chicken-mcwrap-grilled', 'tri-colour-tortilla-strips'),
  ('creamy-chipotle-chicken-mcwrap-grilled', 'white-flour-tortilla'),
  ('dasani-water', 'dasani-water'),
  ('diet-coke-medium', 'diet-coke'),
  ('diet-coke-medium', 'ice'),
  ('double-big-mac-200946', 'beef-patty'),
  ('double-big-mac-200946', 'big-mac-bun'),
  ('double-big-mac-200946', 'big-mac-sauce'),
  ('double-big-mac-200946', 'grill-seasoning'),
  ('double-big-mac-200946', 'lettuce'),
  ('double-big-mac-200946', 'onions-dehydrated'),
  ('double-big-mac-200946', 'pickle-slices'),
  ('double-big-mac-200946', 'processed-cheese'),
  ('double-cheeseburger', 'beef-patty'),
  ('double-cheeseburger', 'grill-seasoning'),
  ('double-cheeseburger', 'ketchup'),
  ('double-cheeseburger', 'mustard'),
  ('double-cheeseburger', 'onions-dehydrated'),
  ('double-cheeseburger', 'pickle-slices'),
  ('double-cheeseburger', 'processed-cheese'),
  ('double-cheeseburger', 'regular-bun'),
  ('double-espresso', 'espresso-coffee'),
  ('double-filet-o-fish', 'filet-o-fish-portion'),
  ('double-filet-o-fish', 'processed-cheese'),
  ('double-filet-o-fish', 'regular-bun'),
  ('double-filet-o-fish', 'tartar-sauce'),
  ('double-hamburger', 'beef-patty'),
  ('double-hamburger', 'grill-seasoning'),
  ('double-hamburger', 'ketchup'),
  ('double-hamburger', 'mustard'),
  ('double-hamburger', 'onions-dehydrated'),
  ('double-hamburger', 'pickle-slices'),
  ('double-hamburger', 'regular-bun'),
  ('double-quarter-pounder-blt', 'bacon-slice'),
  ('double-quarter-pounder-blt', 'grill-seasoning'),
  ('double-quarter-pounder-blt', 'ketchup'),
  ('double-quarter-pounder-blt', 'leaf-lettuce'),
  ('double-quarter-pounder-blt', 'mayonnaise-style-sauce'),
  ('double-quarter-pounder-blt', 'mustard'),
  ('double-quarter-pounder-blt', 'pickle-slices'),
  ('double-quarter-pounder-blt', 'processed-cheese'),
  ('double-quarter-pounder-blt', 'quarter-pounder-beef-patty'),
  ('double-quarter-pounder-blt', 'sesame-seed-bun'),
  ('double-quarter-pounder-blt', 'slivered-onions'),
  ('double-quarter-pounder-blt', 'tomato-slice'),
  ('double-quarter-pounder-with-cheese', 'grill-seasoning'),
  ('double-quarter-pounder-with-cheese', 'ketchup'),
  ('double-quarter-pounder-with-cheese', 'mustard'),
  ('double-quarter-pounder-with-cheese', 'pickle-slices'),
  ('double-quarter-pounder-with-cheese', 'processed-cheese'),
  ('double-quarter-pounder-with-cheese', 'quarter-pounder-beef-patty'),
  ('double-quarter-pounder-with-cheese', 'sesame-seed-bun'),
  ('double-quarter-pounder-with-cheese', 'slivered-onions'),
  ('double-quarter-pounder-without-cheese', 'grill-seasoning'),
  ('double-quarter-pounder-without-cheese', 'ketchup'),
  ('double-quarter-pounder-without-cheese', 'mustard'),
  ('double-quarter-pounder-without-cheese', 'pickle-slices'),
  ('double-quarter-pounder-without-cheese', 'quarter-pounder-beef-patty'),
  ('double-quarter-pounder-without-cheese', 'sesame-seed-bun'),
  ('double-quarter-pounder-without-cheese', 'slivered-onions'),
  ('egg-blt-mcmuffin', 'bacon-slice'),
  ('egg-blt-mcmuffin', 'butter'),
  ('egg-blt-mcmuffin', 'egg'),
  ('egg-blt-mcmuffin', 'english-muffin'),
  ('egg-blt-mcmuffin', 'leaf-lettuce'),
  ('egg-blt-mcmuffin', 'mayonnaise-style-sauce'),
  ('egg-blt-mcmuffin', 'processed-cheese'),
  ('egg-blt-mcmuffin', 'tomato-slice'),
  ('egg-blt-mcmuffin-with-shredded-lettuce', 'bacon-slice'),
  ('egg-blt-mcmuffin-with-shredded-lettuce', 'butter'),
  ('egg-blt-mcmuffin-with-shredded-lettuce', 'egg'),
  ('egg-blt-mcmuffin-with-shredded-lettuce', 'english-muffin'),
  ('egg-blt-mcmuffin-with-shredded-lettuce', 'lettuce'),
  ('egg-blt-mcmuffin-with-shredded-lettuce', 'mayonnaise-style-sauce'),
  ('egg-blt-mcmuffin-with-shredded-lettuce', 'processed-cheese'),
  ('egg-blt-mcmuffin-with-shredded-lettuce', 'tomato-slice'),
  ('egg-blt-with-everything-bagel', 'bacon-slice'),
  ('egg-blt-with-everything-bagel', 'butter'),
  ('egg-blt-with-everything-bagel', 'egg'),
  ('egg-blt-with-everything-bagel', 'everything-bagel'),
  ('egg-blt-with-everything-bagel', 'leaf-lettuce'),
  ('egg-blt-with-everything-bagel', 'mayonnaise-style-sauce'),
  ('egg-blt-with-everything-bagel', 'tomato-slice'),
  ('egg-blt-with-plain-bagel', 'bacon-slice'),
  ('egg-blt-with-plain-bagel', 'butter'),
  ('egg-blt-with-plain-bagel', 'egg'),
  ('egg-blt-with-plain-bagel', 'leaf-lettuce'),
  ('egg-blt-with-plain-bagel', 'mayonnaise-style-sauce'),
  ('egg-blt-with-plain-bagel', 'regular-bagel'),
  ('egg-blt-with-plain-bagel', 'tomato-slice'),
  ('egg-blt-with-sesame-seed-bagel', 'bacon-slice'),
  ('egg-blt-with-sesame-seed-bagel', 'butter'),
  ('egg-blt-with-sesame-seed-bagel', 'egg'),
  ('egg-blt-with-sesame-seed-bagel', 'leaf-lettuce'),
  ('egg-blt-with-sesame-seed-bagel', 'mayonnaise-style-sauce'),
  ('egg-blt-with-sesame-seed-bagel', 'sesame-seed-bagel'),
  ('egg-blt-with-sesame-seed-bagel', 'tomato-slice'),
  ('egg-mcmuffin', 'butter'),
  ('egg-mcmuffin', 'canadian-bacon'),
  ('egg-mcmuffin', 'egg'),
  ('egg-mcmuffin', 'english-muffin'),
  ('egg-mcmuffin', 'processed-cheese'),
  ('egg-n-cheese-mcgriddles', 'egg'),
  ('egg-n-cheese-mcgriddles', 'mcgriddles-cakes'),
  ('egg-n-cheese-mcgriddles', 'processed-cheese'),
  ('egg-n-cheese-mcmuffin', 'butter'),
  ('egg-n-cheese-mcmuffin', 'egg'),
  ('egg-n-cheese-mcmuffin', 'english-muffin'),
  ('egg-n-cheese-mcmuffin', 'processed-cheese'),
  ('english-muffin-with-butter', 'butter'),
  ('english-muffin-with-butter', 'english-muffin'),
  ('espresso', 'espresso-coffee'),
  ('everything-bagel-with-butter', 'butter'),
  ('everything-bagel-with-butter', 'everything-bagel'),
  ('everything-bagel-with-plain-cream-cheese', 'everything-bagel'),
  ('everything-bagel-with-plain-cream-cheese', 'philadelphia-plain-cream-cheese-product'),
  ('filet-o-fish', 'filet-o-fish-portion'),
  ('filet-o-fish', 'processed-cheese'),
  ('filet-o-fish', 'regular-bun'),
  ('filet-o-fish', 'tartar-sauce'),
  ('franks-original-mcveggie', 'crunchy-breaded-veggie-patty'),
  ('franks-original-mcveggie', 'frank-s-redhot-thick-sauce-thick-cayenne-pepper-sauce'),
  ('franks-original-mcveggie', 'lettuce'),
  ('franks-original-mcveggie', 'mayonnaise-style-sauce'),
  ('franks-original-mcveggie', 'sesame-seed-bun'),
  ('franks-redhot-creamy-garlic-bacon-n-egg-mcmuffin', 'bacon-slice'),
  ('franks-redhot-creamy-garlic-bacon-n-egg-mcmuffin', 'butter'),
  ('franks-redhot-creamy-garlic-bacon-n-egg-mcmuffin', 'egg'),
  ('franks-redhot-creamy-garlic-bacon-n-egg-mcmuffin', 'english-muffin'),
  ('franks-redhot-creamy-garlic-bacon-n-egg-mcmuffin', 'frank-s-redhot-creamy-garlic-sauce'),
  ('franks-redhot-creamy-garlic-bacon-n-egg-mcmuffin', 'processed-cheese'),
  ('franks-redhot-creamy-garlic-chicken-mcmuffin', 'butter'),
  ('franks-redhot-creamy-garlic-chicken-mcmuffin', 'english-muffin'),
  ('franks-redhot-creamy-garlic-chicken-mcmuffin', 'frank-s-redhot-creamy-garlic-sauce'),
  ('franks-redhot-creamy-garlic-chicken-mcmuffin', 'junior-chicken-patty'),
  ('franks-redhot-creamy-garlic-chicken-mcmuffin', 'processed-cheese'),
  ('franks-redhot-creamy-garlic-egg-mcmuffin', 'butter'),
  ('franks-redhot-creamy-garlic-egg-mcmuffin', 'canadian-bacon'),
  ('franks-redhot-creamy-garlic-egg-mcmuffin', 'egg'),
  ('franks-redhot-creamy-garlic-egg-mcmuffin', 'english-muffin'),
  ('franks-redhot-creamy-garlic-egg-mcmuffin', 'frank-s-redhot-creamy-garlic-sauce'),
  ('franks-redhot-creamy-garlic-egg-mcmuffin', 'processed-cheese'),
  ('franks-redhot-creamy-garlic-sausage-n-egg-mcmuffin', 'butter'),
  ('franks-redhot-creamy-garlic-sausage-n-egg-mcmuffin', 'egg'),
  ('franks-redhot-creamy-garlic-sausage-n-egg-mcmuffin', 'english-muffin'),
  ('franks-redhot-creamy-garlic-sausage-n-egg-mcmuffin', 'frank-s-redhot-creamy-garlic-sauce'),
  ('franks-redhot-creamy-garlic-sausage-n-egg-mcmuffin', 'processed-cheese'),
  ('franks-redhot-creamy-garlic-sausage-n-egg-mcmuffin', 'sausage-patty'),
  ('franks-redhot-original-mccrispy', 'crispy-chicken-portion'),
  ('franks-redhot-original-mccrispy', 'frank-s-redhot-thick-sauce-thick-cayenne-pepper-sauce'),
  ('franks-redhot-original-mccrispy', 'lettuce'),
  ('franks-redhot-original-mccrispy', 'mayonnaise-style-sauce'),
  ('franks-redhot-original-mccrispy', 'potato-bun'),
  ('franks-redhot-original-mccrispy-bacon-deluxe', 'bacon-slice'),
  ('franks-redhot-original-mccrispy-bacon-deluxe', 'crispy-chicken-portion'),
  ('franks-redhot-original-mccrispy-bacon-deluxe', 'frank-s-redhot-thick-sauce-thick-cayenne-pepper-sauce'),
  ('franks-redhot-original-mccrispy-bacon-deluxe', 'lettuce'),
  ('franks-redhot-original-mccrispy-bacon-deluxe', 'mayonnaise-style-sauce'),
  ('franks-redhot-original-mccrispy-bacon-deluxe', 'potato-bun'),
  ('franks-redhot-original-mccrispy-bacon-deluxe', 'tomato-slice'),
  ('french-fries-medium', 'french-fries'),
  ('french-fries-medium', 'salt'),
  ('french-fries-small-mcpicks', 'french-fries'),
  ('french-fries-small-mcpicks', 'salt'),
  ('french-vanilla-latte-with-2-milk-medium', '2-milk'),
  ('french-vanilla-latte-with-2-milk-medium', 'espresso-coffee'),
  ('french-vanilla-latte-with-2-milk-medium', 'french-vanilla-flavoured-syrup'),
  ('fruit-fibre-muffin', 'fruit-and-fibre-muffin'),
  ('fruitopia-orange-groove-medium', 'fruitopia-orange-groove'),
  ('fruitopia-orange-groove-medium', 'ice'),
  ('fruitopia-strawberry-passion-awareness-medium', 'fruitopia-strawberry-passion-awareness'),
  ('fruitopia-strawberry-passion-awareness-medium', 'ice'),
  ('fuze-iced-tea-medium', 'fuze-iced-tea'),
  ('fuze-iced-tea-medium', 'ice'),
  ('habanero-mcchicken-sandwich', 'creamy-habanero-sauce'),
  ('habanero-mcchicken-sandwich', 'lettuce'),
  ('habanero-mcchicken-sandwich', 'mcchicken-portion'),
  ('habanero-mcchicken-sandwich', 'sesame-seed-bun'),
  ('hamburger', 'beef-patty'),
  ('hamburger', 'grill-seasoning'),
  ('hamburger', 'ketchup'),
  ('hamburger', 'mustard'),
  ('hamburger', 'onions-dehydrated'),
  ('hamburger', 'pickle-slices'),
  ('hamburger', 'regular-bun'),
  ('happy-meal-snack-wrap-crispy', 'crispy-chicken-patty'),
  ('happy-meal-snack-wrap-crispy', 'lettuce'),
  ('happy-meal-snack-wrap-crispy', 'mayonnaise-style-sauce'),
  ('happy-meal-snack-wrap-crispy', 'white-flour-tortilla'),
  ('happy-meal-snack-wrap-grilled', 'grilled-chicken-portion'),
  ('happy-meal-snack-wrap-grilled', 'lettuce'),
  ('happy-meal-snack-wrap-grilled', 'mayonnaise-style-sauce'),
  ('happy-meal-snack-wrap-grilled', 'white-flour-tortilla'),
  ('hash-browns', 'hashbrowns'),
  ('hazelnut-cocoa-mcpops', 'hazelnut-and-cocoa-mcpops'),
  ('higgins-burke-hot-chocolate', '18-cream'),
  ('higgins-burke-hot-chocolate', 'hot-chocolate-packet'),
  ('higgins-burke-hot-chocolate', 'water'),
  ('hockey-hero-burger', 'bacon-slice'),
  ('hockey-hero-burger', 'beef-patty'),
  ('hockey-hero-burger', 'grill-seasoning'),
  ('hockey-hero-burger', 'homestyle-mcrib-roll'),
  ('hockey-hero-burger', 'lettuce'),
  ('hockey-hero-burger', 'mayonnaise-style-sauce'),
  ('hockey-hero-burger', 'onions-dehydrated'),
  ('hockey-hero-burger', 'processed-cheese'),
  ('hot-chocolate-with-2-milk-medium', '2-milk'),
  ('hot-chocolate-with-2-milk-medium', 'chocolate-syrup'),
  ('hot-chocolate-with-2-milk-medium', 'whipped-cream'),
  ('hotcakes', 'hotcakes'),
  ('hotcakes-with-syrup-and-butter', 'butter-portion-whipped'),
  ('hotcakes-with-syrup-and-butter', 'hotcake-syrup'),
  ('hotcakes-with-syrup-and-butter', 'hotcakes'),
  ('iced-coffee-medium', '18-cream'),
  ('iced-coffee-medium', 'brewed-coffee'),
  ('iced-coffee-medium', 'liquid-sugar'),
  ('iced-coffee-with-sugar-free-syrup-medium', '18-cream'),
  ('iced-coffee-with-sugar-free-syrup-medium', 'brewed-coffee'),
  ('iced-coffee-with-sugar-free-syrup-medium', 'sugar-free-syrup'),
  ('junior-chicken', 'junior-chicken-patty'),
  ('junior-chicken', 'lettuce'),
  ('junior-chicken', 'mayonnaise-style-sauce'),
  ('junior-chicken', 'regular-bun'),
  ('latte-with-2-milk-medium', '2-milk'),
  ('latte-with-2-milk-medium', 'espresso-coffee'),
  ('latte-with-sugar-free-syrup-with-2-milk-medium', '2-milk'),
  ('latte-with-sugar-free-syrup-with-2-milk-medium', 'espresso-coffee'),
  ('latte-with-sugar-free-syrup-with-2-milk-medium', 'sugar-free-syrup'),
  ('lemon-fruit-splash-medium', 'ice'),
  ('lemon-fruit-splash-medium', 'lemonade-concentrate'),
  ('lemon-fruit-splash-medium', 'water'),
  ('mango-pineapple-smoothie-with-yogurt-medium', 'ice'),
  ('mango-pineapple-smoothie-with-yogurt-medium', 'mango-pineapple-fruit-base'),
  ('mango-pineapple-smoothie-with-yogurt-medium', 'smoothie-yogurt-mix'),
  ('mcchicken', 'lettuce'),
  ('mcchicken', 'mayonnaise-style-sauce'),
  ('mcchicken', 'mcchicken-portion'),
  ('mcchicken', 'sesame-seed-bun'),
  ('mccrispy', 'crispy-chicken-patty'),
  ('mccrispy', 'lettuce'),
  ('mccrispy', 'mayonnaise-style-sauce'),
  ('mccrispy', 'potato-bun'),
  ('mccrispy-bacon-deluxe', 'bacon-slice'),
  ('mccrispy-bacon-deluxe', 'crispy-chicken-patty'),
  ('mccrispy-bacon-deluxe', 'lettuce'),
  ('mccrispy-bacon-deluxe', 'mayonnaise-style-sauce'),
  ('mccrispy-bacon-deluxe', 'potato-bun'),
  ('mccrispy-bacon-deluxe', 'tomato-slice'),
  ('mccrispy-with-grilled-chicken', 'grilled-chicken-portion'),
  ('mccrispy-with-grilled-chicken', 'lettuce'),
  ('mccrispy-with-grilled-chicken', 'mayonnaise-style-sauce'),
  ('mccrispy-with-grilled-chicken', 'potato-bun'),
  ('mcdouble', 'beef-patty'),
  ('mcdouble', 'grill-seasoning'),
  ('mcdouble', 'ketchup'),
  ('mcdouble', 'mustard'),
  ('mcdouble', 'onions-dehydrated'),
  ('mcdouble', 'pickle-slices'),
  ('mcdouble', 'processed-cheese'),
  ('mcdouble', 'regular-bun'),
  ('mcflurry-dessert-crushed-skor-candy-bars-regular-size-portion', 'crushed-skor-candy-bars'),
  ('mcflurry-dessert-crushed-skor-candy-bars-regular-size-portion', 'vanilla-ice-milk'),
  ('mcflurry-oreo-regular-size-portion', 'oreo-mix-in'),
  ('mcflurry-oreo-regular-size-portion', 'vanilla-ice-milk'),
  ('mcveggie', 'crunchy-breaded-veggie-patty'),
  ('mcveggie', 'lettuce'),
  ('mcveggie', 'mayonnaise-style-sauce'),
  ('mcveggie', 'sesame-seed-bun'),
  ('mighty-mcgriddle', 'bacon-slice'),
  ('mighty-mcgriddle', 'egg'),
  ('mighty-mcgriddle', 'mcgriddles-cakes'),
  ('mighty-mcgriddle', 'processed-cheese'),
  ('mighty-mcgriddle', 'sausage-patty'),
  ('mighty-mcmuffin', 'bacon-slice'),
  ('mighty-mcmuffin', 'butter'),
  ('mighty-mcmuffin', 'egg'),
  ('mighty-mcmuffin', 'english-muffin'),
  ('mighty-mcmuffin', 'processed-cheese'),
  ('mighty-mcmuffin', 'sausage-patty'),
  ('mini-fry', 'french-fries'),
  ('mini-fry', 'salt'),
  ('mocha-with-2-milk-medium', '2-milk'),
  ('mocha-with-2-milk-medium', 'chocolate-syrup'),
  ('mocha-with-2-milk-medium', 'espresso-coffee'),
  ('mocha-with-2-milk-medium', 'whipped-cream'),
  ('new-chicken-and-bacon-mcwrap-crispy', 'bacon-slice'),
  ('new-chicken-and-bacon-mcwrap-crispy', 'crispy-chicken-patty'),
  ('new-chicken-and-bacon-mcwrap-crispy', 'cucumber'),
  ('new-chicken-and-bacon-mcwrap-crispy', 'lettuce'),
  ('new-chicken-and-bacon-mcwrap-crispy', 'mayonnaise-style-sauce'),
  ('new-chicken-and-bacon-mcwrap-crispy', 'tomato-slice'),
  ('new-chicken-and-bacon-mcwrap-crispy', 'white-flour-tortilla'),
  ('new-chicken-and-bacon-mcwrap-grilled', 'bacon-slice'),
  ('new-chicken-and-bacon-mcwrap-grilled', 'cucumber'),
  ('new-chicken-and-bacon-mcwrap-grilled', 'grilled-chicken-portion'),
  ('new-chicken-and-bacon-mcwrap-grilled', 'lettuce'),
  ('new-chicken-and-bacon-mcwrap-grilled', 'mayonnaise-style-sauce'),
  ('new-chicken-and-bacon-mcwrap-grilled', 'tomato-slice'),
  ('new-chicken-and-bacon-mcwrap-grilled', 'white-flour-tortilla'),
  ('new-sweet-chili-mcwrap-crispy', 'crispy-chicken-patty'),
  ('new-sweet-chili-mcwrap-crispy', 'cucumber'),
  ('new-sweet-chili-mcwrap-crispy', 'lettuce'),
  ('new-sweet-chili-mcwrap-crispy', 'mayonnaise-style-sauce'),
  ('new-sweet-chili-mcwrap-crispy', 'sweet-chili-sauce'),
  ('new-sweet-chili-mcwrap-crispy', 'white-flour-tortilla'),
  ('new-sweet-chili-mcwrap-grilled', 'cucumber'),
  ('new-sweet-chili-mcwrap-grilled', 'grilled-chicken-portion'),
  ('new-sweet-chili-mcwrap-grilled', 'lettuce'),
  ('new-sweet-chili-mcwrap-grilled', 'mayonnaise-style-sauce'),
  ('new-sweet-chili-mcwrap-grilled', 'sweet-chili-sauce'),
  ('new-sweet-chili-mcwrap-grilled', 'white-flour-tortilla'),
  ('nite-sprite-medium', 'blue-raspberry-flavoured-syrup'),
  ('nite-sprite-medium', 'ice'),
  ('nite-sprite-medium', 'sprite'),
  ('oat-iced-coffee-medium', 'brewed-coffee'),
  ('oat-iced-coffee-medium', 'ice'),
  ('oat-iced-coffee-medium', 'liquid-sugar'),
  ('oat-iced-coffee-medium', 'oat-beverage'),
  ('oat-iced-coffee-medium', 'water'),
  ('orange-juice-medium', 'orange-juice'),
  ('plain-bagel-with-butter', 'butter'),
  ('plain-bagel-with-butter', 'regular-bagel'),
  ('plain-bagel-with-plain-cream-cheese', 'philadelphia-plain-cream-cheese-product'),
  ('plain-bagel-with-plain-cream-cheese', 'regular-bagel'),
  ('poutine', 'cheese-curds'),
  ('poutine', 'french-fries'),
  ('poutine', 'poutine-gravy'),
  ('poutine', 'salt'),
  ('premium-tea-medium', 'premium-tea'),
  ('quarter-pounder-blt', 'bacon-slice'),
  ('quarter-pounder-blt', 'grill-seasoning'),
  ('quarter-pounder-blt', 'ketchup'),
  ('quarter-pounder-blt', 'leaf-lettuce'),
  ('quarter-pounder-blt', 'mayonnaise-style-sauce'),
  ('quarter-pounder-blt', 'mustard'),
  ('quarter-pounder-blt', 'pickle-slices'),
  ('quarter-pounder-blt', 'processed-cheese'),
  ('quarter-pounder-blt', 'quarter-pounder-beef-patty'),
  ('quarter-pounder-blt', 'sesame-seed-bun'),
  ('quarter-pounder-blt', 'slivered-onions'),
  ('quarter-pounder-blt', 'tomato-slice'),
  ('quarter-pounder-with-cheese', 'grill-seasoning'),
  ('quarter-pounder-with-cheese', 'ketchup'),
  ('quarter-pounder-with-cheese', 'mustard'),
  ('quarter-pounder-with-cheese', 'pickle-slices'),
  ('quarter-pounder-with-cheese', 'processed-cheese'),
  ('quarter-pounder-with-cheese', 'quarter-pounder-beef-patty'),
  ('quarter-pounder-with-cheese', 'sesame-seed-bun'),
  ('quarter-pounder-with-cheese', 'slivered-onions'),
  ('quarter-pounder-without-cheese', 'grill-seasoning'),
  ('quarter-pounder-without-cheese', 'ketchup'),
  ('quarter-pounder-without-cheese', 'mustard'),
  ('quarter-pounder-without-cheese', 'pickle-slices'),
  ('quarter-pounder-without-cheese', 'quarter-pounder-beef-patty'),
  ('quarter-pounder-without-cheese', 'sesame-seed-bun'),
  ('quarter-pounder-without-cheese', 'slivered-onions'),
  ('rainbow-sprinkle-cookie', 'rainbow-sprinkle-cookie'),
  ('ranch-chicken-snack-wrap-crispy-for-relaunch', 'crispy-chicken-patty'),
  ('ranch-chicken-snack-wrap-crispy-for-relaunch', 'lettuce'),
  ('ranch-chicken-snack-wrap-crispy-for-relaunch', 'premium-ranch-sauce'),
  ('ranch-chicken-snack-wrap-crispy-for-relaunch', 'shredded-cheddar-cheese'),
  ('ranch-chicken-snack-wrap-crispy-for-relaunch', 'white-flour-tortilla'),
  ('ranch-chicken-snack-wrap-grilled-for-relaunch', 'grilled-chicken-portion'),
  ('ranch-chicken-snack-wrap-grilled-for-relaunch', 'lettuce'),
  ('ranch-chicken-snack-wrap-grilled-for-relaunch', 'premium-ranch-sauce'),
  ('ranch-chicken-snack-wrap-grilled-for-relaunch', 'shredded-cheddar-cheese'),
  ('ranch-chicken-snack-wrap-grilled-for-relaunch', 'white-flour-tortilla'),
  ('salted-caramel-iced-coffee-medium', '18-cream'),
  ('salted-caramel-iced-coffee-medium', 'brewed-coffee'),
  ('salted-caramel-iced-coffee-medium', 'ice'),
  ('salted-caramel-iced-coffee-medium', 'salted-caramel-flavoured-syrup'),
  ('salted-caramel-iced-coffee-medium', 'water'),
  ('salted-caramel-latte-medium', '2-milk'),
  ('salted-caramel-latte-medium', 'espresso-coffee'),
  ('salted-caramel-latte-medium', 'salted-caramel-flavoured-syrup'),
  ('salted-caramel-mcFlurry-regular', 'hot-caramel-topping'),
  ('salted-caramel-mcFlurry-regular', 'salted-caramel-crunch-topping'),
  ('salted-caramel-mcFlurry-regular', 'vanilla-ice-milk'),
  ('sausage-bacon-egg-breakfast-wrap', 'bacon-slice'),
  ('sausage-bacon-egg-breakfast-wrap', 'egg'),
  ('sausage-bacon-egg-breakfast-wrap', 'hashbrowns'),
  ('sausage-bacon-egg-breakfast-wrap', 'mayonnaise-style-sauce'),
  ('sausage-bacon-egg-breakfast-wrap', 'processed-cheese'),
  ('sausage-bacon-egg-breakfast-wrap', 'sausage-patty'),
  ('sausage-bacon-egg-breakfast-wrap', 'white-flour-tortilla'),
  ('sausage-egg-cheese-mcgriddles', 'egg'),
  ('sausage-egg-cheese-mcgriddles', 'mcgriddles-cakes'),
  ('sausage-egg-cheese-mcgriddles', 'processed-cheese'),
  ('sausage-egg-cheese-mcgriddles', 'sausage-patty'),
  ('sausage-mcgriddles', 'mcgriddles-cakes'),
  ('sausage-mcgriddles', 'sausage-patty'),
  ('sausage-mcmuffin', 'butter'),
  ('sausage-mcmuffin', 'english-muffin'),
  ('sausage-mcmuffin', 'processed-cheese'),
  ('sausage-mcmuffin', 'sausage-patty'),
  ('sausage-n-egg-mcmuffin', 'butter'),
  ('sausage-n-egg-mcmuffin', 'egg'),
  ('sausage-n-egg-mcmuffin', 'english-muffin'),
  ('sausage-n-egg-mcmuffin', 'processed-cheese'),
  ('sausage-n-egg-mcmuffin', 'sausage-patty'),
  ('sausage-n-egg-with-everything-bagel', 'butter'),
  ('sausage-n-egg-with-everything-bagel', 'egg'),
  ('sausage-n-egg-with-everything-bagel', 'everything-bagel'),
  ('sausage-n-egg-with-everything-bagel', 'processed-cheese'),
  ('sausage-n-egg-with-everything-bagel', 'sausage-patty'),
  ('sausage-n-egg-with-plain-bagel', 'butter'),
  ('sausage-n-egg-with-plain-bagel', 'egg'),
  ('sausage-n-egg-with-plain-bagel', 'processed-cheese'),
  ('sausage-n-egg-with-plain-bagel', 'regular-bagel'),
  ('sausage-n-egg-with-plain-bagel', 'sausage-patty'),
  ('sausage-n-egg-with-sesame-seed-bagel', 'butter'),
  ('sausage-n-egg-with-sesame-seed-bagel', 'egg'),
  ('sausage-n-egg-with-sesame-seed-bagel', 'processed-cheese'),
  ('sausage-n-egg-with-sesame-seed-bagel', 'sausage-patty'),
  ('sausage-n-egg-with-sesame-seed-bagel', 'sesame-seed-bagel'),
  ('sesame-seed-bagel-95g-with-plain-cream-cheese', 'philadelphia-plain-cream-cheese-product'),
  ('sesame-seed-bagel-95g-with-plain-cream-cheese', 'sesame-seed-bagel'),
  ('sesame-seed-bagel-with-butter-qc-only', 'butter'),
  ('sesame-seed-bagel-with-butter-qc-only', 'sesame-seed-bagel'),
  ('smarties-mcflurry-regular-size-portion', 'crushed-smarties'),
  ('smarties-mcflurry-regular-size-portion', 'vanilla-ice-milk'),
  ('spicy-bacon-deluxe-grilled-chicken-sandwich', 'bacon-slice'),
  ('spicy-bacon-deluxe-grilled-chicken-sandwich', 'creamy-habanero-sauce'),
  ('spicy-bacon-deluxe-grilled-chicken-sandwich', 'grilled-chicken-portion'),
  ('spicy-bacon-deluxe-grilled-chicken-sandwich', 'lettuce'),
  ('spicy-bacon-deluxe-grilled-chicken-sandwich', 'potato-bun'),
  ('spicy-bacon-deluxe-grilled-chicken-sandwich', 'tomato-slice'),
  ('spicy-buffalo-chicken-poutine', 'cheese-curds'),
  ('spicy-buffalo-chicken-poutine', 'crispy-chicken-portion'),
  ('spicy-buffalo-chicken-poutine', 'french-fries'),
  ('spicy-buffalo-chicken-poutine', 'green-onions'),
  ('spicy-buffalo-chicken-poutine', 'poutine-gravy'),
  ('spicy-buffalo-chicken-poutine', 'salt'),
  ('spicy-buffalo-chicken-poutine', 'spicy-buffalo-sauce'),
  ('spicy-buffalo-snack-wrap-crispy', 'crispy-chicken-patty'),
  ('spicy-buffalo-snack-wrap-crispy', 'lettuce'),
  ('spicy-buffalo-snack-wrap-crispy', 'shredded-cheddar-cheese'),
  ('spicy-buffalo-snack-wrap-crispy', 'spicy-buffalo-sauce'),
  ('spicy-buffalo-snack-wrap-crispy', 'white-flour-tortilla'),
  ('spicy-buffalo-snack-wrap-grilled', 'grilled-chicken-portion'),
  ('spicy-buffalo-snack-wrap-grilled', 'lettuce'),
  ('spicy-buffalo-snack-wrap-grilled', 'shredded-cheddar-cheese'),
  ('spicy-buffalo-snack-wrap-grilled', 'spicy-buffalo-sauce'),
  ('spicy-buffalo-snack-wrap-grilled', 'white-flour-tortilla'),
  ('spicy-egg-hash-brown-breakfast-wrap', 'creamy-habanero-sauce'),
  ('spicy-egg-hash-brown-breakfast-wrap', 'egg'),
  ('spicy-egg-hash-brown-breakfast-wrap', 'hashbrowns'),
  ('spicy-egg-hash-brown-breakfast-wrap', 'lettuce'),
  ('spicy-egg-hash-brown-breakfast-wrap', 'processed-cheese'),
  ('spicy-egg-hash-brown-breakfast-wrap', 'tomato-slice'),
  ('spicy-egg-hash-brown-breakfast-wrap', 'white-flour-tortilla'),
  ('spicy-grilled-chicken-sandwich', 'creamy-habanero-sauce'),
  ('spicy-grilled-chicken-sandwich', 'grilled-chicken-portion'),
  ('spicy-grilled-chicken-sandwich', 'lettuce'),
  ('spicy-grilled-chicken-sandwich', 'potato-bun'),
  ('spicy-mccrispy', 'creamy-habanero-sauce'),
  ('spicy-mccrispy', 'crispy-chicken-patty'),
  ('spicy-mccrispy', 'lettuce'),
  ('spicy-mccrispy', 'potato-bun'),
  ('spicy-mccrispy-bacon-deluxe', 'bacon-slice'),
  ('spicy-mccrispy-bacon-deluxe', 'creamy-habanero-sauce'),
  ('spicy-mccrispy-bacon-deluxe', 'crispy-chicken-patty'),
  ('spicy-mccrispy-bacon-deluxe', 'lettuce'),
  ('spicy-mccrispy-bacon-deluxe', 'potato-bun'),
  ('spicy-mccrispy-bacon-deluxe', 'tomato-slice'),
  ('spicy-mcveggie', 'creamy-habanero-sauce'),
  ('spicy-mcveggie', 'crunchy-breaded-veggie-patty'),
  ('spicy-mcveggie', 'lettuce'),
  ('spicy-mcveggie', 'sesame-seed-bun'),
  ('sprite-medium', 'ice'),
  ('sprite-medium', 'sprite'),
  ('strawberry-banana-smoothie-with-yogurt-medium', 'ice'),
  ('strawberry-banana-smoothie-with-yogurt-medium', 'smoothie-yogurt-mix'),
  ('strawberry-banana-smoothie-with-yogurt-medium', 'strawberry-banana-fruit-smoothie-base'),
  ('strawberry-flavoured-yogurt-tube', 'strawberry-yogurt-tube'),
  ('sundae-hot-caramel', 'hot-caramel-topping'),
  ('sundae-hot-caramel', 'vanilla-ice-milk'),
  ('sundae-hot-fudge', 'hot-fudge-sundae-topping'),
  ('sundae-hot-fudge', 'vanilla-ice-milk'),
  ('sundae-strawberry', 'strawberry-sauce'),
  ('sundae-strawberry', 'vanilla-ice-milk'),
  ('sweet-chili-junior-chicken', 'junior-chicken-patty'),
  ('sweet-chili-junior-chicken', 'lettuce'),
  ('sweet-chili-junior-chicken', 'mayonnaise-style-sauce'),
  ('sweet-chili-junior-chicken', 'regular-bun'),
  ('sweet-chili-junior-chicken', 'sweet-chili-sauce'),
  ('toasted-smores-cookie', 'toasted-s-mores-cookie'),
  ('triple-thick-milkshake-chocolate-medium', 'triple-thick-milkshake-chocolate-syrup'),
  ('triple-thick-milkshake-chocolate-medium', 'vanilla-ice-milk'),
  ('triple-thick-milkshake-strawberry-medium', 'triple-thick-milkshake-strawberry-syrup'),
  ('triple-thick-milkshake-strawberry-medium', 'vanilla-ice-milk'),
  ('triple-thick-milkshake-vanilla-medium', 'triple-thick-milkshake-vanilla-syrup'),
  ('triple-thick-milkshake-vanilla-medium', 'vanilla-ice-milk'),
  ('triple-thick-shamrock-shake-syrup-medium', 'triple-thick-shamrock-shake-syrup'),
  ('triple-thick-shamrock-shake-syrup-medium', 'vanilla-ice-milk'),
  ('vanilla-chai-iced-frapp-small', 'ice'),
  ('vanilla-chai-iced-frapp-small', 'vanilla-chai-frapp-base'),
  ('vanilla-iced-coffee-medium', '18-cream'),
  ('vanilla-iced-coffee-medium', 'brewed-coffee'),
  ('vanilla-iced-coffee-medium', 'french-vanilla-flavoured-syrup'),
  ('watermelon-lime-fruit-splash-medium', 'ice'),
  ('watermelon-lime-fruit-splash-medium', 'lemonade-concentrate'),
  ('watermelon-lime-fruit-splash-medium', 'water'),
  ('watermelon-lime-fruit-splash-medium', 'watermelon-lime-flavoured-syrup'),
  ('white-chocolate-mcpops', 'white-chocolate-mcpops')
;

insert into ingredient_allergens (ingredient_id, allergen_id) values
  ('1-partly-skimmed-chocolate-milk', 'milk'),
  ('1-partly-skimmed-milk', 'milk'),
  ('18-cream', 'milk'),
  ('2-milk', 'milk'),
  ('baked-apple-pie', 'soy'),
  ('baked-apple-pie', 'wheat'),
  ('banana-chocolate-chunk-muffin', 'egg'),
  ('banana-chocolate-chunk-muffin', 'milk'),
  ('banana-chocolate-chunk-muffin', 'oat'),
  ('banana-chocolate-chunk-muffin', 'soy'),
  ('banana-chocolate-chunk-muffin', 'wheat'),
  ('berry-mcpops-donut', 'egg'),
  ('berry-mcpops-donut', 'milk'),
  ('berry-mcpops-donut', 'wheat'),
  ('big-mac-bun', 'sesame-seeds'),
  ('big-mac-bun', 'wheat'),
  ('big-mac-sauce', 'egg'),
  ('big-mac-sauce', 'mustard'),
  ('big-mac-sauce', 'soy'),
  ('big-mac-sauce', 'wheat'),
  ('blueberry-cream-cheese-pie', 'milk'),
  ('blueberry-cream-cheese-pie', 'soy'),
  ('blueberry-cream-cheese-pie', 'wheat'),
  ('blueberry-muffin', 'egg'),
  ('blueberry-muffin', 'milk'),
  ('blueberry-muffin', 'oat'),
  ('blueberry-muffin', 'soy'),
  ('blueberry-muffin', 'wheat'),
  ('butter', 'milk'),
  ('butter-portion-whipped', 'milk'),
  ('cadbury-chocolate', 'milk'),
  ('cadbury-chocolate', 'soy'),
  ('caramel-flavoured-syrup', 'milk'),
  ('caramel-flavoured-syrup', 'soy'),
  ('carrot-muffin', 'egg'),
  ('carrot-muffin', 'milk'),
  ('carrot-muffin', 'oat'),
  ('carrot-muffin', 'soy'),
  ('carrot-muffin', 'wheat'),
  ('cheese-curds', 'milk'),
  ('chicken-big-mac-patty', 'wheat'),
  ('chicken-mcnuggets', 'wheat'),
  ('chocolate-brownie-muffin-mix', 'egg'),
  ('chocolate-brownie-muffin-mix', 'milk'),
  ('chocolate-brownie-muffin-mix', 'soy'),
  ('chocolate-brownie-muffin-mix', 'wheat'),
  ('chocolate-chip-muffin', 'egg'),
  ('chocolate-chip-muffin', 'milk'),
  ('chocolate-chip-muffin', 'soy'),
  ('chocolate-chip-muffin', 'wheat'),
  ('chocolate-chunk-cookie', 'barley'),
  ('chocolate-chunk-cookie', 'egg'),
  ('chocolate-chunk-cookie', 'milk'),
  ('chocolate-chunk-cookie', 'soy'),
  ('chocolate-chunk-cookie', 'wheat'),
  ('chocolate-syrup', 'milk'),
  ('coffee-frappe', 'milk'),
  ('cranberry-orange-muffin', 'egg'),
  ('cranberry-orange-muffin', 'milk'),
  ('cranberry-orange-muffin', 'soy'),
  ('cranberry-orange-muffin', 'wheat'),
  ('creamy-chipotle-sauce', 'egg'),
  ('creamy-chipotle-sauce', 'mustard'),
  ('creamy-habanero-sauce', 'egg'),
  ('creamy-habanero-sauce', 'mustard'),
  ('crispy-chicken-patty', 'wheat'),
  ('crispy-chicken-portion', 'wheat'),
  ('crunchy-breaded-veggie-patty', 'oat'),
  ('crunchy-breaded-veggie-patty', 'soy'),
  ('crunchy-breaded-veggie-patty', 'wheat'),
  ('crushed-skor-candy-bars', 'milk'),
  ('crushed-skor-candy-bars', 'soy'),
  ('crushed-skor-candy-bars', 'tree-nuts'),
  ('crushed-smarties', 'milk'),
  ('crushed-smarties', 'soy'),
  ('crushed-smarties', 'wheat'),
  ('egg', 'egg'),
  ('egg', 'milk'),
  ('egg-mixture', 'egg'),
  ('egg-mixture', 'milk'),
  ('english-muffin', 'barley'),
  ('english-muffin', 'wheat'),
  ('everything-bagel', 'sesame-seeds'),
  ('everything-bagel', 'wheat'),
  ('filet-o-fish-portion', 'fish'),
  ('filet-o-fish-portion', 'wheat'),
  ('frank-s-redhot-creamy-garlic-sauce', 'egg'),
  ('frank-s-redhot-creamy-garlic-sauce', 'milk'),
  ('french-vanilla-flavoured-syrup', 'milk'),
  ('french-vanilla-flavoured-syrup', 'soy'),
  ('fruit-and-fibre-muffin', 'egg'),
  ('fruit-and-fibre-muffin', 'milk'),
  ('fruit-and-fibre-muffin', 'oat'),
  ('fruit-and-fibre-muffin', 'soy'),
  ('fruit-and-fibre-muffin', 'wheat'),
  ('hazelnut-and-cocoa-mcpops', 'egg'),
  ('hazelnut-and-cocoa-mcpops', 'milk'),
  ('hazelnut-and-cocoa-mcpops', 'soy'),
  ('hazelnut-and-cocoa-mcpops', 'tree-nuts'),
  ('homestyle-mcrib-roll', 'wheat'),
  ('hot-caramel-topping', 'milk'),
  ('hot-chocolate-packet', 'milk'),
  ('hot-fudge-sundae-topping', 'milk'),
  ('hot-fudge-sundae-topping', 'soy'),
  ('hotcakes', 'egg'),
  ('hotcakes', 'milk'),
  ('hotcakes', 'soy'),
  ('hotcakes', 'wheat'),
  ('junior-chicken-patty', 'wheat'),
  ('large-cone', 'soy'),
  ('large-cone', 'wheat'),
  ('mayonnaise-style-sauce', 'egg'),
  ('mayonnaise-style-sauce', 'mustard'),
  ('mcchicken-portion', 'soy'),
  ('mcchicken-portion', 'wheat'),
  ('mcgriddles-cakes', 'barley'),
  ('mcgriddles-cakes', 'milk'),
  ('mcgriddles-cakes', 'soy'),
  ('mcgriddles-cakes', 'wheat'),
  ('mustard', 'mustard'),
  ('oreo-mix-in', 'soy'),
  ('oreo-mix-in', 'wheat'),
  ('philadelphia-plain-cream-cheese-product', 'milk'),
  ('potato-bun', 'wheat'),
  ('premium-ranch-sauce', 'egg'),
  ('premium-ranch-sauce', 'milk'),
  ('processed-cheese', 'milk'),
  ('processed-cheese', 'soy'),
  ('rainbow-sprinkle-cookie', 'barley'),
  ('rainbow-sprinkle-cookie', 'egg'),
  ('rainbow-sprinkle-cookie', 'milk'),
  ('rainbow-sprinkle-cookie', 'soy'),
  ('rainbow-sprinkle-cookie', 'wheat'),
  ('regular-bagel', 'barley'),
  ('regular-bagel', 'wheat'),
  ('regular-bun', 'wheat'),
  ('sesame-seed-bagel', 'barley'),
  ('sesame-seed-bagel', 'sesame-seeds'),
  ('sesame-seed-bagel', 'wheat'),
  ('sesame-seed-bun', 'sesame-seeds'),
  ('sesame-seed-bun', 'wheat'),
  ('shredded-cheddar-cheese', 'milk'),
  ('smoothie-yogurt-mix', 'milk'),
  ('spicy-buffalo-sauce', 'milk'),
  ('strawberry-yogurt-tube', 'milk'),
  ('sugar-free-syrup', 'sulphites'),
  ('tartar-sauce', 'egg'),
  ('tartar-sauce', 'mustard'),
  ('toasted-s-mores-cookie', 'barley'),
  ('toasted-s-mores-cookie', 'egg'),
  ('toasted-s-mores-cookie', 'milk'),
  ('toasted-s-mores-cookie', 'soy'),
  ('toasted-s-mores-cookie', 'wheat'),
  ('vanilla-chai-frapp-base', 'milk'),
  ('vanilla-ice-milk', 'milk'),
  ('whipped-cream', 'milk'),
  ('white-chocolate-mcpops', 'egg'),
  ('white-chocolate-mcpops', 'milk'),
  ('white-chocolate-mcpops', 'soy'),
  ('white-chocolate-mcpops', 'wheat'),
  ('white-flour-tortilla', 'wheat')
;
