apiVersion: v1
kind: ConfigMap
metadata:
  name: ntfy-config
  namespace: ntfy
data:
  NTFY_BASE_URL: https://ntfy.webguru.ca
  NTFY_LISTEN_HTTP: :80
  NTFY_CACHE_FILE: /var/lib/ntfy/cache.db
  NTFY_AUTH_FILE: /var/lib/ntfy/auth.db
  NTFY_AUTH_DEFAULT_ACCESS: deny-all
  NTFY_BEHIND_PROXY: "true"
  NTFY_ENABLE_LOGIN: "true"
